-- CORRECTIF HYDRA
-- À exécuter dans Supabase SQL Editor après les corrections GitHub.

create table if not exists public.hydra_access_assignments (
  id bigint generated by default as identity primary key,
  access_id bigint not null references public.list_access_codes(id) on delete cascade,
  hydra_player_name text not null,
  private_token text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(access_id, hydra_player_name)
);

create index if not exists hydra_access_assignments_access_idx
  on public.hydra_access_assignments(access_id);

alter table public.hydra_access_assignments enable row level security;
revoke all on table public.hydra_access_assignments from anon, authenticated;

drop function if exists public.admin_sync_hydra_access_assignments(bigint,jsonb);

create or replace function public.admin_sync_hydra_access_assignments(
  p_access_id bigint,
  p_players jsonb default '[]'::jsonb
)
returns table(
  assignment_id bigint,
  access_id bigint,
  person_name text,
  hydra_player_name text,
  private_token text,
  active_assignment boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code_exists boolean;
  v_name text;
  v_private_token text;
begin
  perform public.assert_admin_header();

  if not exists(
    select 1 from public.list_access_codes where id=p_access_id
  ) then
    raise exception 'Accès introuvable.';
  end if;

  if p_players is null or jsonb_typeof(p_players) <> 'array' then
    raise exception 'La sélection Hydra est invalide.';
  end if;

  -- Vérification de chaque personnage demandé.
  for v_name in
    select distinct trim(value)
    from jsonb_array_elements_text(p_players) value
    where trim(value) <> ''
  loop
    if not exists(
      select 1
      from jsonb_array_elements(
        coalesce(
          (select settings->'murder_party'->'players'
           from public.birthday_config
           where id=1),
          '[]'::jsonb
        )
      ) p
      where lower(trim(p->>'name')) = lower(v_name)
    ) then
      raise exception 'Joueur Hydra introuvable : %.', v_name;
    end if;
  end loop;

  -- Retire uniquement les dossiers désélectionnés.
  delete from public.hydra_access_assignments haa
  where haa.access_id=p_access_id
    and not exists(
      select 1
      from jsonb_array_elements_text(p_players) value
      where lower(trim(value)) = lower(trim(haa.hydra_player_name))
    );

  -- Ajoute ou réactive les dossiers sélectionnés.
  for v_name in
    select distinct trim(value)
    from jsonb_array_elements_text(p_players) value
    where trim(value) <> ''
  loop
    if not exists(
      select 1
      from public.hydra_access_assignments
      where access_id=p_access_id
        and lower(trim(hydra_player_name))=lower(v_name)
    ) then
      loop
        v_private_token :=
          'HYDRA-' ||
          upper(substr(
            md5(
              random()::text ||
              clock_timestamp()::text ||
              p_access_id::text ||
              v_name
            ),
            1,
            24
          ));

        v_code_exists := exists(
          select 1
          from public.hydra_access_assignments
          where private_token=v_private_token
        );

        exit when not v_code_exists;
      end loop;

      insert into public.hydra_access_assignments(
        access_id,
        hydra_player_name,
        private_token,
        active
      )
      values(
        p_access_id,
        v_name,
        v_private_token,
        true
      );
    else
      update public.hydra_access_assignments
      set active=true
      where access_id=p_access_id
        and lower(trim(hydra_player_name))=lower(v_name);
    end if;
  end loop;

  return query
  select
    haa.id,
    haa.access_id,
    (select label from public.list_access_codes where id=haa.access_id),
    haa.hydra_player_name,
    haa.private_token,
    haa.active
  from public.hydra_access_assignments haa
  where haa.access_id=p_access_id
  order by haa.created_at asc;
end;
$$;

grant execute on function public.admin_sync_hydra_access_assignments(bigint,jsonb) to anon;

notify pgrst,'reload schema';
