(()=>{'use strict';if(window.__hydraAudio)return;window.__hydraAudio=true;
const K='hydra_audio_settings_v1',S=Object.assign({enabled:true,volume:.22},JSON.parse(localStorage.getItem(K)||'{}'));
let c=null,m=null,started=false;
const save=()=>localStorage.setItem(K,JSON.stringify(S));
function ensure(){if(c)return c;const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;c=new A();m=c.createGain();m.gain.value=S.enabled?S.volume:0;m.connect(c.destination);return c}
async function start(){const x=ensure();if(!x)return;if(x.state==='suspended')try{await x.resume()}catch{}if(started)return;started=true;const g=x.createGain(),o=x.createOscillator();g.gain.value=.012;o.type='sine';o.frequency.value=55;o.connect(g).connect(m);o.start();window.__hydraAudioAmbient={o,g}}
function tone(k){if(!S.enabled)return;const x=ensure();if(!x)return;start();const p={click:[520,.05,'square',.018],open:[220,.12,'sine',.045],success:[660,.12,'sine',.05],alert:[150,.2,'sawtooth',.035],boot:[110,.4,'triangle',.04]}[k]||[520,.05,'square',.018],n=x.currentTime,o=x.createOscillator(),g=x.createGain();o.type=p[2];o.frequency.setValueAtTime(p[0],n);if(k==='success')o.frequency.exponentialRampToValueAtTime(990,n+.12);g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(p[3],n+.008);g.gain.exponentialRampToValueAtTime(.0001,n+p[1]);o.connect(g).connect(m);o.start(n);o.stop(n+p[1]+.02)}
function enabled(v){S.enabled=!!v;save();const x=ensure();if(x)m.gain.setTargetAtTime(S.enabled?S.volume:0,x.currentTime,.04);render()}
function volume(v){S.volume=Math.max(0,Math.min(1,Number(v)/100));save();const x=ensure();if(x&&S.enabled)m.gain.setTargetAtTime(S.volume,x.currentTime,.04);render()}
function render(){const b=document.getElementById('hydraAudioToggle'),r=document.getElementById('hydraAudioVolume'),l=document.getElementById('hydraAudioLabel');if(b){b.textContent=S.enabled?'🔊':'🔇';b.setAttribute('aria-label',S.enabled?'Désactiver les sons':'Activer les sons')}if(r)r.value=String(Math.round(S.volume*100));if(l)l.textContent=Math.round(S.volume*100)+'%'}
function ui(){const st=document.createElement('style');st.textContent='.hydra-audio{position:fixed;right:14px;bottom:14px;z-index:100001;display:flex;align-items:center;gap:7px;padding:7px 9px;border:1px solid #304563;border-radius:13px;background:rgba(8,14,24,.92);backdrop-filter:blur(12px);box-shadow:0 12px 35px #0008}.hydra-audio button{border:1px solid #3b5272;background:#101b2b;color:#eef5ff;border-radius:9px;width:34px;height:30px;cursor:pointer}.hydra-audio input{width:76px}.hydra-audio small{color:#8fa5c2;font:700 10px ui-monospace,SFMono-Regular,Consolas,monospace;min-width:30px;text-align:right}@media(max-width:620px){.hydra-audio{right:9px;bottom:9px}.hydra-audio input{width:58px}}';document.head.appendChild(st);const h=document.createElement('div');h.className='hydra-audio';h.innerHTML='<button id="hydraAudioToggle" type="button"></button><input id="hydraAudioVolume" type="range" min="0" max="100" step="1"><small id="hydraAudioLabel"></small>';document.body.appendChild(h);document.getElementById('hydraAudioToggle').onclick=()=>{if(!S.enabled){enabled(true);start();tone('open')}else enabled(false)};document.getElementById('hydraAudioVolume').oninput=e=>{volume(e.target.value);if(S.enabled)start()};render()}
function bind(){document.addEventListener('pointerdown',e=>{if(e.target.closest('.hydra-audio'))return;if(S.enabled){start();if(e.target.closest('button,.tab,.vm-icon,.vm-task-btn,.mini-btn,.cmd-chip,.forensic-btn'))tone('click')}},{passive:true});document.addEventListener('keydown',e=>{if(S.enabled&&(e.key==='Enter'||e.key==='Escape')){start();tone('click')}},{passive:true});const f=window.__hydraStartVM;if(f&&!f.__audioWrapped){const w=async function(){start();tone('boot');return f.apply(this,arguments)};w.__audioWrapped=true;window.__hydraStartVM=w}}
window.hydraSound=tone;window.hydraAudio={start,setEnabled:enabled,setVolume:volume,state:S};document.addEventListener('DOMContentLoaded',()=>{ui();bind();setTimeout(bind,500)});})();