create table if not exists public.reservations (
  gift_id text primary key,
  name text not null check (char_length(trim(name)) between 1 and 50),
  created_at timestamptz not null default now()
);

alter table public.reservations enable row level security;

drop policy if exists "Public can view reservations" on public.reservations;
create policy "Public can view reservations"
on public.reservations for select
to anon
using (true);

drop policy if exists "Public can create reservations" on public.reservations;
create policy "Public can create reservations"
on public.reservations for insert
to anon
with check (char_length(trim(name)) between 1 and 50);

-- Autorisations PostgREST pour les visiteurs non connectés
grant usage on schema public to anon;
grant select, insert on table public.reservations to anon;

-- Autoriser la déréservation depuis le site
grant delete on table public.reservations to anon;

drop policy if exists "Public can cancel reservations" on public.reservations;
create policy "Public can cancel reservations"
on public.reservations
for delete
to anon
using (true);

-- Fonction serveur pour déréserver un cadeau en vérifiant le prénom
create or replace function public.cancel_reservation(p_gift_id text, p_name text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted boolean;
begin
  delete from public.reservations
  where gift_id = p_gift_id
    and lower(trim(name)) = lower(trim(p_name))
  returning true into deleted;

  return coalesce(deleted, false);
end;
$$;

grant execute on function public.cancel_reservation(text, text) to anon;

-- Suggestions de cadeaux
create table if not exists public.gift_suggestions (
  id bigint generated by default as identity primary key,
  name text,
  gift_name text not null check (char_length(trim(gift_name)) between 1 and 120),
  link text,
  message text,
  created_at timestamptz not null default now()
);

alter table public.gift_suggestions add column if not exists status text not null default 'pending';
alter table public.gift_suggestions drop constraint if exists gift_suggestions_status_check;
alter table public.gift_suggestions add constraint gift_suggestions_status_check check (status in ('pending','approved','rejected'));

alter table public.gift_suggestions enable row level security;

drop policy if exists "Public can view approved gift suggestions" on public.gift_suggestions;
create policy "Public can view approved gift suggestions"
on public.gift_suggestions for select
to anon
using (status = 'approved');

drop policy if exists "Public can create gift suggestions" on public.gift_suggestions;
create policy "Public can create gift suggestions"
on public.gift_suggestions for insert
to anon
with check (
  char_length(trim(gift_name)) between 1 and 120
  and status = 'pending'
);

grant select, insert on table public.gift_suggestions to anon;
grant usage, select on sequence public.gift_suggestions_id_seq to anon;

-- Participations financières annoncées (aucun paiement n'est effectué ici)
create table if not exists public.contributions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 50),
  amount numeric(10,2) not null check (amount >= 1 and amount <= 5000),
  message text,
  created_at timestamptz not null default now()
);

alter table public.contributions enable row level security;

drop policy if exists "Public can view contributions" on public.contributions;
create policy "Public can view contributions"
on public.contributions for select
to anon
using (true);

drop policy if exists "Public can create contributions" on public.contributions;
create policy "Public can create contributions"
on public.contributions for insert
to anon
with check (
  char_length(trim(name)) between 1 and 50
  and amount >= 1
  and amount <= 5000
);

grant select, insert on table public.contributions to anon;
grant usage, select on sequence public.contributions_id_seq to anon;

-- Boîte à idées
create table if not exists public.ideas (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 50),
  idea text not null check (char_length(trim(idea)) between 1 and 500),
  created_at timestamptz not null default now()
);
alter table public.ideas enable row level security;
drop policy if exists "Public can view ideas" on public.ideas;
create policy "Public can view ideas" on public.ideas for select to anon using (true);
drop policy if exists "Public can create ideas" on public.ideas;
create policy "Public can create ideas" on public.ideas for insert to anon with check (char_length(trim(name)) between 1 and 50 and char_length(trim(idea)) between 1 and 500);
grant select, insert on table public.ideas to anon;
grant usage, select on sequence public.ideas_id_seq to anon;

-- Boîte à messages
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 50),
  message text not null check (char_length(trim(message)) between 1 and 500),
  created_at timestamptz not null default now()
);
alter table public.messages enable row level security;
drop policy if exists "Public can create messages" on public.messages;
create policy "Public can create messages" on public.messages for insert to anon with check (char_length(trim(name)) between 1 and 50 and char_length(trim(message)) between 1 and 500);
revoke select on table public.messages from anon;
grant insert on table public.messages to anon;
grant usage, select on sequence public.messages_id_seq to anon;

-- Retrait sécurisé des propositions
create or replace function public.delete_gift_suggestion(p_id bigint, p_name text)
returns boolean language plpgsql security definer set search_path=public as $$
declare deleted boolean;
begin
  delete from public.gift_suggestions
  where id=p_id and lower(trim(name))=lower(trim(p_name))
  returning true into deleted;
  return coalesce(deleted,false);
end;
$$;
grant execute on function public.delete_gift_suggestion(bigint,text) to anon;

-- Retrait sécurisé des participations
create or replace function public.delete_contribution(p_id bigint, p_name text)
returns boolean language plpgsql security definer set search_path=public as $$
declare deleted boolean;
begin
  delete from public.contributions
  where id=p_id and lower(trim(name))=lower(trim(p_name))
  returning true into deleted;
  return coalesce(deleted,false);
end;
$$;
grant execute on function public.delete_contribution(bigint,text) to anon;

-- Suppression d'une idée
create or replace function public.delete_idea(p_id bigint, p_name text)
returns boolean language plpgsql security definer set search_path=public as $$
declare deleted boolean;
begin
  delete from public.ideas
  where id=p_id and lower(trim(name))=lower(trim(p_name))
  returning true into deleted;
  return coalesce(deleted,false);
end;
$$;
grant execute on function public.delete_idea(bigint,text) to anon;

-- Suppression d'un message
create or replace function public.delete_message(p_id bigint, p_name text)
returns boolean language plpgsql security definer set search_path=public as $$
declare deleted boolean;
begin
  delete from public.messages
  where id=p_id and lower(trim(name))=lower(trim(p_name))
  returning true into deleted;
  return coalesce(deleted,false);
end;
$$;
grant execute on function public.delete_message(bigint,text) to anon;


-- Compte administrateur pour la validation des suggestions
create extension if not exists pgcrypto;

create table if not exists public.site_admin (
  id boolean primary key default true,
  password_hash text not null
);

insert into public.site_admin (id,password_hash)
values (true, crypt('CHANGE_ME_ADMIN_PASSWORD', gen_salt('bf')))
on conflict (id) do nothing;

revoke all on table public.site_admin from anon;

create or replace function public.admin_list_pending_suggestions(p_password text)
returns setof public.gift_suggestions
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.site_admin
    where id = true
      and crypt(p_password, password_hash) = password_hash
  ) then
    raise exception 'unauthorized';
  end if;

  return query
  select *
  from public.gift_suggestions
  where status = 'pending'
  order by created_at asc;
end;
$$;

grant execute on function public.admin_list_pending_suggestions(text) to anon;

create or replace function public.admin_set_suggestion_status(
  p_id bigint,
  p_password text,
  p_status text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.site_admin
    where id = true
      and crypt(p_password, password_hash) = password_hash
  ) then
    raise exception 'unauthorized';
  end if;

  if p_status not in ('approved','rejected') then
    raise exception 'invalid status';
  end if;

  update public.gift_suggestions
  set status = p_status
  where id = p_id
    and status = 'pending';

  return found;
end;
$$;

grant execute on function public.admin_set_suggestion_status(bigint,text,text) to anon;

-- Discussion publique
create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 50),
  message text not null check (char_length(trim(message)) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.community_posts
add column if not exists link text;

alter table public.community_posts
add column if not exists attachments jsonb not null default '[]'::jsonb;

alter table public.community_posts
drop constraint if exists community_posts_attachments_check;

alter table public.community_posts
add constraint community_posts_attachments_check
check (
  jsonb_typeof(attachments) = 'array'
  and jsonb_array_length(attachments) <= 5
);

alter table public.community_posts enable row level security;

drop policy if exists "Public can view community posts" on public.community_posts;
create policy "Public can view community posts"
on public.community_posts for select
to anon
using (true);

drop policy if exists "Public can create community posts" on public.community_posts;
create policy "Public can create community posts"
on public.community_posts for insert
to anon
with check (
  char_length(trim(name)) between 1 and 50
  and char_length(trim(message)) between 1 and 500
);

grant select, insert on table public.community_posts to anon;
grant usage, select on sequence public.community_posts_id_seq to anon;

-- Réactions
create table if not exists public.community_reactions (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.community_posts(id) on delete cascade,
  emoji text not null check (emoji in ('❤️','👍','😂','🎉','😮')),
  created_at timestamptz not null default now()
);

alter table public.community_reactions enable row level security;

drop policy if exists "Public can view reactions" on public.community_reactions;
create policy "Public can view reactions"
on public.community_reactions for select
to anon
using (true);

drop policy if exists "Public can react" on public.community_reactions;
create policy "Public can react"
on public.community_reactions for insert
to anon
with check (emoji in ('❤️','👍','😂','🎉','😮'));

grant select, insert on table public.community_reactions to anon;
grant usage, select on sequence public.community_reactions_id_seq to anon;

-- MessageBox privée: aucune lecture publique
revoke select on table public.messages from anon;
grant insert on table public.messages to anon;


-- =====================================================
-- SUPPRESSION SÉCURISÉE DES MESSAGES + FICHIERS
-- =====================================================

revoke delete on table public.community_posts from anon;

drop policy if exists "Public can delete community posts" on public.community_posts;

create or replace function public.delete_community_post(
  p_id bigint,
  p_name text
)
returns boolean
language plpgsql
security definer
set search_path = public, storage
as $delete$
declare
  post_name text;
  files jsonb;
  file_item jsonb;
  file_path text;
begin
  select name, attachments
  into post_name, files
  from public.community_posts
  where id = p_id;

  if post_name is null
     or lower(trim(post_name)) <> lower(trim(p_name))
  then
    return false;
  end if;

  for file_item in
    select value
    from jsonb_array_elements(coalesce(files, '[]'::jsonb))
  loop
    file_path := regexp_replace(
      file_item->>'url',
      '^.*/storage/v1/object/public/community-files/',
      ''
    );

    if file_path is not null and file_path <> '' then
      delete from storage.objects
      where bucket_id = 'community-files'
        and name = file_path;
    end if;
  end loop;

  delete from public.community_posts
  where id = p_id;

  return true;
end;
$delete$;

grant execute
on function public.delete_community_post(bigint, text)
to anon;


-- =====================================================
-- RÉACTIONS AVEC VÉRIFICATION DU PRÉNOM
-- =====================================================

alter table public.community_reactions
add column if not exists name text not null default 'Ancien';

revoke delete on table public.community_reactions from anon;

drop policy if exists "Public can react" on public.community_reactions;
drop policy if exists "Public can delete reactions" on public.community_reactions;

create policy "Public can react"
on public.community_reactions
for insert
to anon
with check (
  char_length(trim(name)) between 1 and 50
  and emoji in ('❤️','👍','😂','🎉','😮')
);

create or replace function public.toggle_reaction(
  p_post_id bigint,
  p_emoji text,
  p_name text
)
returns text
language plpgsql
security definer
set search_path = public
as $delete$
declare
  reaction_id bigint;
begin
  if char_length(trim(p_name)) < 1
     or char_length(trim(p_name)) > 50
     or p_emoji not in ('❤️','👍','😂','🎉','😮')
  then
    raise exception 'invalid reaction';
  end if;

  delete from public.community_reactions
  where post_id = p_post_id
    and emoji = p_emoji
    and lower(trim(name)) = lower(trim(p_name))
  returning id into reaction_id;

  if reaction_id is not null then
    return 'removed';
  end if;

  insert into public.community_reactions(post_id, emoji, name)
  values (p_post_id, p_emoji, trim(p_name));

  return 'added';
end;
$delete$;

grant execute
on function public.toggle_reaction(bigint, text, text)
to anon;

  
-- =====================================================
-- STOCKAGE PUBLIC : GIFS, IMAGES, DOCUMENTS, VIDEOS...
-- =====================================================

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'community-files',
  'community-files',
  true,
  6291456,
  array[
    'image/*',
    'video/*',
    'audio/*',
    'application/pdf',
    'text/plain',
    'text/csv',
    'application/rtf',
    'application/zip',
    'application/x-7z-compressed',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation'
  ]::text[]
)
on conflict (id) do update
set
  public = true,
  file_size_limit = 6291456,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can upload community files" on storage.objects;
create policy "Public can upload community files"
on storage.objects
for insert
to anon
with check (
  bucket_id = 'community-files'
  and name like 'community/%'
);
