create table if not exists public.reservations (
  gift_id text primary key,
  name text not null check (char_length(trim(name)) between 1 and 50),
  created_at timestamptz not null default now()
);

alter table public.reservations enable row level security;

drop policy if exists "Public can view reservations" on public.reservations;
create policy "Public can view reservations"
on public.reservations for select
to anon
using (true);

drop policy if exists "Public can create reservations" on public.reservations;
create policy "Public can create reservations"
on public.reservations for insert
to anon
with check (char_length(trim(name)) between 1 and 50);

-- Autorisations PostgREST pour les visiteurs non connectés
grant usage on schema public to anon;
grant select, insert on table public.reservations to anon;

-- Autoriser la déréservation depuis le site
grant delete on table public.reservations to anon;

drop policy if exists "Public can cancel reservations" on public.reservations;
create policy "Public can cancel reservations"
on public.reservations
for delete
to anon
using (true);

-- Fonction serveur pour déréserver un cadeau en vérifiant le prénom
create or replace function public.cancel_reservation(p_gift_id text, p_name text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted boolean;
begin
  delete from public.reservations
  where gift_id = p_gift_id
    and lower(trim(name)) = lower(trim(p_name))
  returning true into deleted;

  return coalesce(deleted, false);
end;
$$;

grant execute on function public.cancel_reservation(text, text) to anon;

-- Suggestions de cadeaux
create table if not exists public.gift_suggestions (
  id bigint generated by default as identity primary key,
  name text,
  gift_name text not null check (char_length(trim(gift_name)) between 1 and 120),
  link text,
  message text,
  created_at timestamptz not null default now()
);

alter table public.gift_suggestions add column if not exists status text not null default 'pending';
alter table public.gift_suggestions drop constraint if exists gift_suggestions_status_check;
alter table public.gift_suggestions add constraint gift_suggestions_status_check check (status in ('pending','approved','rejected'));

alter table public.gift_suggestions enable row level security;

drop policy if exists "Public can view approved gift suggestions" on public.gift_suggestions;
create policy "Public can view approved gift suggestions"
on public.gift_suggestions for select
to anon
using (status = 'approved');

drop policy if exists "Public can create gift suggestions" on public.gift_suggestions;
create policy "Public can create gift suggestions"
on public.gift_suggestions for insert
to anon
with check (
  char_length(trim(gift_name)) between 1 and 120
  and status = 'pending'
);

grant select, insert on table public.gift_suggestions to anon;
grant usage, select on sequence public.gift_suggestions_id_seq to anon;

-- Participations financières annoncées (aucun paiement n'est effectué ici)
create table if not exists public.contributions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 50),
  amount numeric(10,2) not null check (amount >= 1 and amount <= 5000),
  message text,
  created_at timestamptz not null default now()
);

alter table public.contributions enable row level security;

drop policy if exists "Public can view contributions" on public.contributions;
create policy "Public can view contributions"
on public.contributions for select
to anon
using (true);

drop policy if exists "Public can create contributions" on public.contributions;
create policy "Public can create contributions"
on public.contributions for insert
to anon
with check (
  char_length(trim(name)) between 1 and 50
  and amount >= 1
  and amount <= 5000
);

grant select, insert on table public.contributions to anon;
grant usage, select on sequence public.contributions_id_seq to anon;

-- Boîte à idées
create table if not exists public.ideas (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 50),
  idea text not null check (char_length(trim(idea)) between 1 and 500),
  created_at timestamptz not null default now()
);
alter table public.ideas enable row level security;
drop policy if exists "Public can view ideas" on public.ideas;
create policy "Public can view ideas" on public.ideas for select to anon using (true);
drop policy if exists "Public can create ideas" on public.ideas;
create policy "Public can create ideas" on public.ideas for insert to anon with check (char_length(trim(name)) between 1 and 50 and char_length(trim(idea)) between 1 and 500);
grant select, insert on table public.ideas to anon;
grant usage, select on sequence public.ideas_id_seq to anon;

-- Boîte à messages
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 50),
  message text not null check (char_length(trim(message)) between 1 and 500),
  created_at timestamptz not null default now()
);
alter table public.messages enable row level security;
drop policy if exists "Public can create messages" on public.messages;
create policy "Public can create messages" on public.messages for insert to anon with check (char_length(trim(name)) between 1 and 50 and char_length(trim(message)) between 1 and 500);
revoke select on table public.messages from anon;
grant insert on table public.messages to anon;
grant usage, select on sequence public.messages_id_seq to anon;

-- Retrait sécurisé des propositions
create or replace function public.delete_gift_suggestion(p_id bigint, p_name text)
returns boolean language plpgsql security definer set search_path=public as $$
declare deleted boolean;
begin
  delete from public.gift_suggestions
  where id=p_id and lower(trim(name))=lower(trim(p_name))
  returning true into deleted;
  return coalesce(deleted,false);
end;
$$;
grant execute on function public.delete_gift_suggestion(bigint,text) to anon;

-- Retrait sécurisé des participations
create or replace function public.delete_contribution(p_id bigint, p_name text)
returns boolean language plpgsql security definer set search_path=public as $$
declare deleted boolean;
begin
  delete from public.contributions
  where id=p_id and lower(trim(name))=lower(trim(p_name))
  returning true into deleted;
  return coalesce(deleted,false);
end;
$$;
grant execute on function public.delete_contribution(bigint,text) to anon;

-- Suppression d'une idée
create or replace function public.delete_idea(p_id bigint, p_name text)
returns boolean language plpgsql security definer set search_path=public as $$
declare deleted boolean;
begin
  delete from public.ideas
  where id=p_id and lower(trim(name))=lower(trim(p_name))
  returning true into deleted;
  return coalesce(deleted,false);
end;
$$;
grant execute on function public.delete_idea(bigint,text) to anon;

-- Suppression d'un message
create or replace function public.delete_message(p_id bigint, p_name text)
returns boolean language plpgsql security definer set search_path=public as $$
declare deleted boolean;
begin
  delete from public.messages
  where id=p_id and lower(trim(name))=lower(trim(p_name))
  returning true into deleted;
  return coalesce(deleted,false);
end;
$$;
grant execute on function public.delete_message(bigint,text) to anon;


create or replace function public.assert_admin_header()
returns void
language plpgsql
security definer
set search_path = public
as $admincheck$
declare
  v_headers jsonb;
  v_code text;
begin
  v_headers := coalesce(nullif(current_setting('request.headers', true), ''), '{}')::jsonb;
  v_code := trim(coalesce(v_headers ->> 'x-admin-code', ''));

  if not exists (
    select 1 from public.list_access_codes
    where active = true and is_admin = true and code = v_code
  ) then
    raise exception 'Accès administrateur refusé.' using errcode = '42501';
  end if;
end;
$admincheck$;

revoke execute on function public.assert_admin_header() from anon, authenticated;

create or replace function public.admin_list_pending_suggestions()
returns setof public.gift_suggestions
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin_header();

  return query
  select *
  from public.gift_suggestions
  where status = 'pending'
  order by created_at asc;
end;
$$;

grant execute on function public.admin_list_pending_suggestions() to anon;

create or replace function public.admin_set_suggestion_status(
  p_id bigint,
    p_status text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin_header();

  if p_status not in ('approved','rejected') then
    raise exception 'invalid status';
  end if;

  update public.gift_suggestions
  set status = p_status
  where id = p_id
    and status = 'pending';

  return found;
end;
$$;

grant execute on function public.admin_set_suggestion_status(bigint, text) to anon;

-- Discussion publique
create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 50),
  message text not null check (char_length(trim(message)) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.community_posts
add column if not exists link text;

alter table public.community_posts
add column if not exists attachments jsonb not null default '[]'::jsonb;

alter table public.community_posts
drop constraint if exists community_posts_attachments_check;

alter table public.community_posts
add constraint community_posts_attachments_check
check (
  jsonb_typeof(attachments) = 'array'
  and jsonb_array_length(attachments) <= 5
);

alter table public.community_posts enable row level security;

drop policy if exists "Public can view community posts" on public.community_posts;
create policy "Public can view community posts"
on public.community_posts for select
to anon
using (true);

drop policy if exists "Public can create community posts" on public.community_posts;
create policy "Public can create community posts"
on public.community_posts for insert
to anon
with check (
  char_length(trim(name)) between 1 and 50
  and char_length(trim(message)) between 1 and 500
);

grant select, insert on table public.community_posts to anon;
grant usage, select on sequence public.community_posts_id_seq to anon;

-- Réactions
create table if not exists public.community_reactions (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.community_posts(id) on delete cascade,
  emoji text not null check (emoji in ('❤️','👍','😂','🎉','😮')),
  created_at timestamptz not null default now()
);

alter table public.community_reactions enable row level security;

drop policy if exists "Public can view reactions" on public.community_reactions;
create policy "Public can view reactions"
on public.community_reactions for select
to anon
using (true);

drop policy if exists "Public can react" on public.community_reactions;
create policy "Public can react"
on public.community_reactions for insert
to anon
with check (emoji in ('❤️','👍','😂','🎉','😮'));

grant select, insert on table public.community_reactions to anon;
grant usage, select on sequence public.community_reactions_id_seq to anon;

-- MessageBox privée: aucune lecture publique
revoke select on table public.messages from anon;
grant insert on table public.messages to anon;


-- =====================================================
-- SUPPRESSION SÉCURISÉE DES MESSAGES + FICHIERS
-- =====================================================

revoke delete on table public.community_posts from anon;

drop policy if exists "Public can delete community posts" on public.community_posts;

create or replace function public.delete_community_post(
  p_id bigint,
  p_name text
)
returns boolean
language plpgsql
security definer
set search_path = public, storage
as $delete$
declare
  post_name text;
  files jsonb;
  file_item jsonb;
  file_path text;
begin
  select name, attachments
  into post_name, files
  from public.community_posts
  where id = p_id;

  if post_name is null
     or lower(trim(post_name)) <> lower(trim(p_name))
  then
    return false;
  end if;

  for file_item in
    select value
    from jsonb_array_elements(coalesce(files, '[]'::jsonb))
  loop
    file_path := regexp_replace(
      file_item->>'url',
      '^.*/storage/v1/object/public/community-files/',
      ''
    );

    if file_path is not null and file_path <> '' then
      delete from storage.objects
      where bucket_id = 'community-files'
        and name = file_path;
    end if;
  end loop;

  delete from public.community_posts
  where id = p_id;

  return true;
end;
$delete$;

grant execute
on function public.delete_community_post(bigint, text)
to anon;


-- =====================================================
-- RÉACTIONS AVEC VÉRIFICATION DU PRÉNOM
-- =====================================================

alter table public.community_reactions
add column if not exists name text not null default 'Ancien';

revoke delete on table public.community_reactions from anon;

drop policy if exists "Public can react" on public.community_reactions;
drop policy if exists "Public can delete reactions" on public.community_reactions;

create policy "Public can react"
on public.community_reactions
for insert
to anon
with check (
  char_length(trim(name)) between 1 and 50
  and emoji in ('❤️','👍','😂','🎉','😮')
);

create or replace function public.toggle_reaction(
  p_post_id bigint,
  p_emoji text,
  p_name text
)
returns text
language plpgsql
security definer
set search_path = public
as $delete$
declare
  reaction_id bigint;
begin
  if char_length(trim(p_name)) < 1
     or char_length(trim(p_name)) > 50
     or p_emoji not in ('❤️','👍','😂','🎉','😮')
  then
    raise exception 'invalid reaction';
  end if;

  delete from public.community_reactions
  where post_id = p_post_id
    and emoji = p_emoji
    and lower(trim(name)) = lower(trim(p_name))
  returning id into reaction_id;

  if reaction_id is not null then
    return 'removed';
  end if;

  insert into public.community_reactions(post_id, emoji, name)
  values (p_post_id, p_emoji, trim(p_name));

  return 'added';
end;
$delete$;

grant execute
on function public.toggle_reaction(bigint, text, text)
to anon;

  
-- ============================================================
-- COMMUNAUTÉ PRIVÉE : code d'accès + identité automatique
-- ============================================================

revoke select, insert, update, delete on table public.community_posts from anon, authenticated;
revoke select, insert, update, delete on table public.community_reactions from anon, authenticated;
revoke execute on function public.toggle_reaction(bigint,text,text) from anon, authenticated;
revoke execute on function public.delete_community_post(bigint,text) from anon, authenticated;

create or replace function public.get_private_community(p_code text)
returns table (
  id bigint, name text, message text, link text, attachments jsonb, created_at timestamptz,
  heart bigint, thumbs bigint, laugh bigint, party bigint, wow bigint
)
language plpgsql
security definer
set search_path = public
as $privatecommunity$
begin
  if not exists (
    select 1 from public.list_access_codes
    where active = true and code = trim(coalesce(p_code, ''))
  ) then
    raise exception 'Accès refusé.' using errcode = '42501';
  end if;

  return query
  select
    p.id, p.name, p.message, p.link, p.attachments, p.created_at,
    count(r.id) filter (where r.emoji = '❤️')::bigint,
    count(r.id) filter (where r.emoji = '👍')::bigint,
    count(r.id) filter (where r.emoji = '😂')::bigint,
    count(r.id) filter (where r.emoji = '🎉')::bigint,
    count(r.id) filter (where r.emoji = '😮')::bigint
  from public.community_posts p
  left join public.community_reactions r on r.post_id = p.id
  group by p.id
  order by p.created_at desc
  limit 50;
end;
$privatecommunity$;

grant execute on function public.get_private_community(text) to anon;


create or replace function public.create_private_community_post(
  p_code text, p_message text, p_link text default null, p_attachments jsonb default '[]'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $privatepost$
declare
  v_name text;
  v_id bigint;
begin
  select label into v_name
  from public.list_access_codes
  where active = true and code = trim(coalesce(p_code, ''))
  limit 1;

  if v_name is null then
    raise exception 'Accès refusé.' using errcode = '42501';
  end if;

  if char_length(trim(coalesce(p_message, ''))) < 1
     or char_length(trim(p_message)) > 500 then
    raise exception 'Message invalide.';
  end if;

  if p_link is not null and char_length(trim(p_link)) > 500 then
    raise exception 'Lien invalide.';
  end if;

  p_attachments := coalesce(p_attachments, '[]'::jsonb);
  if jsonb_typeof(p_attachments) <> 'array' or jsonb_array_length(p_attachments) > 5 then
    raise exception 'Pièces jointes invalides.';
  end if;

  insert into public.community_posts(name, message, link, attachments)
  values (
    trim(v_name), trim(p_message), nullif(trim(coalesce(p_link, '')), ''), p_attachments
  )
  returning id into v_id;

  return v_id;
end;
$privatepost$;

grant execute on function public.create_private_community_post(text,text,text,jsonb) to anon;


create or replace function public.toggle_private_community_reaction(
  p_code text, p_post_id bigint, p_emoji text
)
returns text
language plpgsql
security definer
set search_path = public
as $privatereaction$
declare
  v_name text;
  reaction_id bigint;
begin
  select label into v_name
  from public.list_access_codes
  where active = true and code = trim(coalesce(p_code, ''))
  limit 1;

  if v_name is null then
    raise exception 'Accès refusé.' using errcode = '42501';
  end if;

  if p_emoji not in ('❤️','👍','😂','🎉','😮') then
    raise exception 'Réaction invalide.';
  end if;

  delete from public.community_reactions
  where post_id = p_post_id
    and emoji = p_emoji
    and lower(trim(name)) = lower(trim(v_name))
  returning id into reaction_id;

  if reaction_id is not null then
    return 'removed';
  end if;

  if not exists (select 1 from public.community_posts where id = p_post_id) then
    raise exception 'Message introuvable.';
  end if;

  insert into public.community_reactions(post_id, emoji, name)
  values (p_post_id, p_emoji, trim(v_name));

  return 'added';
end;
$privatereaction$;

grant execute on function public.toggle_private_community_reaction(text,bigint,text) to anon;


create or replace function public.delete_private_community_post(
  p_code text, p_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public, storage
as $privatedelete$
declare
  v_name text;
  files jsonb;
  file_item jsonb;
  file_path text;
begin
  select label into v_name
  from public.list_access_codes
  where active = true and code = trim(coalesce(p_code, ''))
  limit 1;

  if v_name is null then
    raise exception 'Accès refusé.' using errcode = '42501';
  end if;

  select attachments into files
  from public.community_posts
  where id = p_id and lower(trim(name)) = lower(trim(v_name));

  if files is null then return false; end if;

  for file_item in select value from jsonb_array_elements(coalesce(files, '[]'::jsonb))
  loop
    file_path := regexp_replace(
      file_item->>'url',
      '^.*/storage/v1/object/public/community-files/', ''
    );

    if file_path is not null and file_path <> '' then
      delete from storage.objects
      where bucket_id = 'community-files' and name = file_path;
    end if;
  end loop;

  delete from public.community_posts
  where id = p_id and lower(trim(name)) = lower(trim(v_name));

  return found;
end;
$privatedelete$;

grant execute on function public.delete_private_community_post(text,bigint) to anon;


-- ============================================================
-- FIN COMMUNAUTÉ PRIVÉE
-- ============================================================

-- =====================================================
-- STOCKAGE PUBLIC : GIFS, IMAGES, DOCUMENTS, VIDEOS...
-- =====================================================

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'community-files',
  'community-files',
  true,
  6291456,
  array[
    'image/*',
    'video/*',
    'audio/*',
    'application/pdf',
    'text/plain',
    'text/csv',
    'application/rtf',
    'application/zip',
    'application/x-7z-compressed',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation'
  ]::text[]
)
on conflict (id) do update
set
  public = true,
  file_size_limit = 6291456,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can upload community files" on storage.objects;
create policy "Public can upload community files"
on storage.objects
for insert
to anon
with check (
  bucket_id = 'community-files'
  and name like 'community/%'
  and exists (
    select 1 from public.list_access_codes
    where active = true
      and code = trim(
        coalesce(
          (coalesce(nullif(current_setting('request.headers', true), ''), '{}')::jsonb)->>'x-access-code',
          ''
        )
      )
  )
);


-- =====================================================
-- CAGNOTTES / PROJETS DE FINANCEMENT
-- =====================================================

create table if not exists public.fundraisers (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) between 1 and 120),
  description text,
  goal_amount numeric(10,2) not null check (goal_amount > 0 and goal_amount <= 50000),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

alter table public.fundraisers enable row level security;

drop policy if exists "Public can view approved fundraisers" on public.fundraisers;
create policy "Public can view approved fundraisers"
on public.fundraisers
for select
to anon
using (status = 'approved');

drop policy if exists "Public can create fundraisers" on public.fundraisers;
create policy "Public can create fundraisers"
on public.fundraisers
for insert
to anon
with check (
  char_length(trim(title)) between 1 and 120
  and goal_amount > 0
  and goal_amount <= 50000
  and status = 'pending'
);

grant select, insert on table public.fundraisers to anon;
grant usage, select on sequence public.fundraisers_id_seq to anon;

-- Rattachement facultatif des participations à une cagnotte
alter table public.contributions
add column if not exists fundraiser_id bigint references public.fundraisers(id) on delete set null;

drop policy if exists "Public can view contributions" on public.contributions;
create policy "Public can view contributions"
on public.contributions
for select
to anon
using (true);

drop policy if exists "Public can create contributions" on public.contributions;
create policy "Public can create contributions"
on public.contributions
for insert
to anon
with check (
  char_length(trim(name)) between 1 and 50
  and amount >= 1
  and amount <= 5000
  and (
    fundraiser_id is null
    or exists (
      select 1 from public.fundraisers f
      where f.id = fundraiser_id
        and f.status = 'approved'
    )
  )
);

grant select, insert on table public.contributions to anon;

-- Validation des nouvelles cagnottes par l’administrateur
create or replace function public.admin_list_all_fundraisers()
returns setof public.fundraisers
language plpgsql
security definer
set search_path = public
as $fundall$
begin
  perform public.assert_admin_header();
  return query
  select * from public.fundraisers
  order by created_at desc;
end;
$fundall$;

grant execute on function public.admin_list_all_fundraisers() to anon;

create or replace function public.admin_list_pending_fundraisers()
returns setof public.fundraisers
language plpgsql
security definer
set search_path = public
as $fundadmin$
begin
  perform public.assert_admin_header();

  return query
  select *
  from public.fundraisers
  where status = 'pending'
  order by created_at asc;
end;
$fundadmin$;

grant execute on function public.admin_list_pending_fundraisers() to anon;

create or replace function public.admin_set_fundraiser_status(
  p_id bigint,
    p_status text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $fundstatus$
begin
  perform public.assert_admin_header();

  if p_status not in ('approved','rejected') then
    raise exception 'invalid status';
  end if;

  update public.fundraisers
  set status = p_status
  where id = p_id
    and status = 'pending';

  return found;
end;
$fundstatus$;

grant execute on function public.admin_set_fundraiser_status(bigint, text) to anon;

-- =====================================================
-- ============================================================
-- ADMIN : liste consolidée des accès + profils
-- Utilise des noms de sortie distincts pour éviter toute ambiguïté
-- avec les colonnes de tables.
-- ============================================================
create or replace function public.admin_list_people_access()
returns table(
  access_id bigint,
  person_name text,
  access_code text,
  active_access boolean,
  is_admin_access boolean,
  access_created_at timestamptz,
  last_used_at timestamptz,
  profile_id bigint,
  relation text,
  avatar text,
  bio text,
  profile_created_at timestamptz,
  profile_updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $peopleaccess$
begin
  perform public.assert_admin_header();

  return query
  select
    lac.id as access_id,
    lac.label as person_name,
    lac.code as access_code,
    lac.active as active_access,
    lac.is_admin as is_admin_access,
    lac.created_at as access_created_at,
    lac.last_used_at,
    gp.id as profile_id,
    gp.relation,
    gp.avatar,
    gp.bio,
    gp.created_at as profile_created_at,
    gp.updated_at as profile_updated_at
  from public.list_access_codes as lac
  left join public.guest_profiles as gp
    on lower(trim(gp.name)) = lower(trim(lac.label))
  order by lac.created_at desc;
end;
$peopleaccess$;

grant execute on function public.admin_list_people_access() to anon;

create or replace function public.admin_list_access_usage()
returns table(
  access_id bigint,
  person_name text,
  access_code text,
  active_access boolean,
  is_admin_access boolean,
  authorization_count bigint,
  last_authorized_at timestamptz,
  duplicate_count_for_name bigint
)
language plpgsql
security definer
set search_path = public
as $accessusage$
begin
  perform public.assert_admin_header();

  return query
  select
    lac.id as access_id,
    lac.label as person_name,
    lac.code as access_code,
    lac.active as active_access,
    lac.is_admin as is_admin_access,
    count(la.id)::bigint as authorization_count,
    max(la.authorized_at) as last_authorized_at,
    (
      select count(*)
      from public.list_access_codes dup
      where lower(trim(dup.label)) = lower(trim(lac.label))
    )::bigint as duplicate_count_for_name
  from public.list_access_codes as lac
  left join public.list_access_authorizations as la
    on la.access_id = lac.id
  group by lac.id,lac.label,lac.code,lac.active,lac.is_admin
  order by lac.created_at desc;
end;
$accessusage$;

grant execute on function public.admin_list_access_usage() to anon;

create or replace function public.admin_list_access_stats()
returns table(
  active_accesses bigint,
  total_access_codes bigint,
  total_authorizations bigint,
  used_accesses bigint,
  duplicate_people bigint
)
language plpgsql
security definer
set search_path = public
as $accessstats$
begin
  perform public.assert_admin_header();

  return query
  select
    (select count(*) from public.list_access_codes where active=true)::bigint,
    (select count(*) from public.list_access_codes)::bigint,
    (select count(*) from public.list_access_authorizations)::bigint,
    (select count(distinct access_id) from public.list_access_authorizations)::bigint,
    (
      select count(*)
      from (
        select lower(trim(label)) as normalized_label
        from public.list_access_codes
        group by lower(trim(label))
        having count(*) > 1
      ) d
    )::bigint;
end;
$accessstats$;

grant execute on function public.admin_list_access_stats() to anon;

create or replace function public.admin_list_access_duplicates()
returns table(
  person_name text,
  access_count bigint,
  access_codes text
)
language plpgsql
security definer
set search_path = public
as $accessdups$
begin
  perform public.assert_admin_header();

  return query
  select
    min(lac.label) as person_name,
    count(*)::bigint as access_count,
    string_agg(lac.code, ', ' order by lac.created_at desc) as access_codes
  from public.list_access_codes as lac
  group by lower(trim(lac.label))
  having count(*) > 1
  order by count(*) desc, min(lac.label);
end;
$accessdups$;

grant execute on function public.admin_list_access_duplicates() to anon;



-- TABLEAU ADMINISTRATEUR : MESSAGES, IDÉES, PARTICIPATIONS, COMMUNAUTÉ
-- =====================================================

create or replace function public.admin_list_messages()
returns setof public.messages
language plpgsql
security definer
set search_path = public
as $adminmsg$
begin
  perform public.assert_admin_header();

  return query
  select *
  from public.messages
  order by created_at desc;
end;
$adminmsg$;

grant execute on function public.admin_list_messages() to anon;


create or replace function public.admin_list_ideas()
returns setof public.ideas
language plpgsql
security definer
set search_path = public
as $adminidea$
begin
  perform public.assert_admin_header();

  return query
  select *
  from public.ideas
  order by created_at desc;
end;
$adminidea$;

grant execute on function public.admin_list_ideas() to anon;


create or replace function public.admin_list_contributions()
returns table (
  id bigint,
  name text,
  amount numeric,
  message text,
  created_at timestamptz,
  fundraiser_id bigint,
  fundraiser_title text
)
language plpgsql
security definer
set search_path = public
as $admincontrib$
begin
  perform public.assert_admin_header();

  return query
  select
    c.id,
    c.name,
    c.amount,
    c.message,
    c.created_at,
    c.fundraiser_id,
    f.title
  from public.contributions c
  left join public.fundraisers f on f.id = c.fundraiser_id
  order by c.created_at desc;
end;
$admincontrib$;

grant execute on function public.admin_list_contributions() to anon;


create or replace function public.admin_list_community_posts()
returns setof public.community_posts
language plpgsql
security definer
set search_path = public
as $admincommunity$
begin
  perform public.assert_admin_header();

  return query
  select *
  from public.community_posts
  order by created_at desc;
end;
$admincommunity$;

grant execute on function public.admin_list_community_posts() to anon;


create or replace function public.admin_delete_message(
  p_id bigint
  )
returns boolean
language plpgsql
security definer
set search_path = public
as $adminmsgdel$
begin
  perform public.assert_admin_header();

  delete from public.messages where id = p_id;
  return found;
end;
$adminmsgdel$;

grant execute on function public.admin_delete_message(bigint) to anon;


create or replace function public.admin_delete_idea(
  p_id bigint
  )
returns boolean
language plpgsql
security definer
set search_path = public
as $adminideadel$
begin
  perform public.assert_admin_header();

  delete from public.ideas where id = p_id;
  return found;
end;
$adminideadel$;

grant execute on function public.admin_delete_idea(bigint) to anon;


create or replace function public.admin_delete_contribution(
  p_id bigint
  )
returns boolean
language plpgsql
security definer
set search_path = public
as $admincontribdel$
begin
  perform public.assert_admin_header();

  delete from public.contributions where id = p_id;
  return found;
end;
$admincontribdel$;

grant execute on function public.admin_delete_contribution(bigint) to anon;


create or replace function public.admin_delete_community_post(
  p_id bigint
  )
returns boolean
language plpgsql
security definer
set search_path = public, storage
as $admincommunitydel$
declare
  files jsonb;
  file_item jsonb;
  file_path text;
begin
  perform public.assert_admin_header();

  select attachments
  into files
  from public.community_posts
  where id = p_id;

  if files is null then
    return false;
  end if;

  for file_item in
    select value
    from jsonb_array_elements(coalesce(files, '[]'::jsonb))
  loop
    file_path := regexp_replace(
      file_item->>'url',
      '^.*/storage/v1/object/public/community-files/',
      ''
    );

    if file_path is not null and file_path <> '' then
      delete from storage.objects
      where bucket_id = 'community-files'
        and name = file_path;
    end if;
  end loop;

  delete from public.community_posts where id = p_id;
  return found;
end;
$admincommunitydel$;

grant execute on function public.admin_delete_community_post(bigint) to anon;


-- =====================================================
-- OUTILS ADMIN : SUPPRESSION + ANNONCES
-- =====================================================

create or replace function public.admin_delete_suggestion(p_id bigint)
returns boolean language plpgsql security definer set search_path=public as $admsuggdel$
begin
  perform public.assert_admin_header();
  delete from public.gift_suggestions where id=p_id;
  return found;
end;
$admsuggdel$;
grant execute on function public.admin_delete_suggestion(bigint) to anon;

create or replace function public.admin_delete_fundraiser(p_id bigint)
returns boolean language plpgsql security definer set search_path=public as $admfunddel$
begin
  perform public.assert_admin_header();
  delete from public.fundraisers where id=p_id;
  return found;
end;
$admfunddel$;
grant execute on function public.admin_delete_fundraiser(bigint) to anon;

create or replace function public.admin_create_announcement(p_message text,p_link text default null)
returns bigint language plpgsql security definer set search_path=public as $admannounce$
declare new_id bigint;
begin
  perform public.assert_admin_header();
  if char_length(trim(coalesce(p_message,''))) < 1 or char_length(trim(p_message)) > 500 then
    raise exception 'invalid announcement';
  end if;
  if p_link is not null and char_length(trim(p_link)) > 500 then
    raise exception 'invalid announcement link';
  end if;
  insert into public.community_posts(name,message,link)
  values ('📢 Ethan',trim(p_message),nullif(trim(p_link),''))
  returning id into new_id;
  return new_id;
end;
$admannounce$;
grant execute on function public.admin_create_announcement(text,text) to anon;


-- =====================================================
-- JOURNAL D'ACTIVITÉ DU SITE + STATISTIQUES ADMIN
-- =====================================================

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_name text not null default 'Visiteur',
  action text not null,
  entity_type text not null,
  entity_id text,
  details text,
  created_at timestamptz not null default now()
);

alter table public.audit_logs enable row level security;
revoke all on table public.audit_logs from anon, authenticated;
grant usage, select on sequence public.audit_logs_id_seq to anon;

create index if not exists audit_logs_created_at_idx
on public.audit_logs(created_at desc);

create or replace function public.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $audit$
declare
  row_data jsonb;
  old_data jsonb;
  actor text;
  entity_key text;
  detail text;
  action_name text;
  old_status text;
  new_status text;
begin
  row_data := case when TG_OP = 'DELETE' then to_jsonb(OLD) else to_jsonb(NEW) end;
  old_data := case when TG_OP = 'INSERT' then '{}'::jsonb else to_jsonb(OLD) end;

  actor := coalesce(
    nullif(trim(row_data->>'name'), ''),
    'Visiteur'
  );

  entity_key := coalesce(row_data->>'id', row_data->>'gift_id');

  old_status := coalesce(old_data->>'status', '');
  new_status := coalesce(row_data->>'status', '');

  if TG_OP = 'UPDATE'
     and TG_TABLE_NAME in ('gift_suggestions','fundraisers')
     and old_status <> new_status
  then
    action_name := case
      when new_status = 'approved' then 'validée'
      when new_status = 'rejected' then 'refusée'
      else 'modifiée'
    end;
  else
    action_name := case TG_OP
      when 'INSERT' then 'créée'
      when 'UPDATE' then 'modifiée'
      when 'DELETE' then 'supprimée'
      else lower(TG_OP)
    end;
  end if;

  detail := coalesce(
    nullif(trim(row_data->>'gift_name'), ''),
    nullif(trim(row_data->>'title'), ''),
    nullif(trim(row_data->>'gift_id'), ''),
    case when TG_TABLE_NAME = 'community_reactions'
      then 'Réaction ' || coalesce(row_data->>'emoji','')
    end,
    TG_TABLE_NAME
  );

  insert into public.audit_logs(actor_name, action, entity_type, entity_id, details)
  values (
    actor,
    action_name,
    case TG_TABLE_NAME
      when 'gift_suggestions' then 'Suggestion'
      when 'fundraisers' then 'Cagnotte'
      when 'contributions' then 'Participation'
      when 'messages' then 'Message'
      when 'ideas' then 'Idée'
      when 'community_posts' then 'Communauté'
      when 'community_reactions' then 'Réaction'
      when 'reservations' then 'Réservation'
      else TG_TABLE_NAME
    end,
    entity_key,
    detail
  );

  return case when TG_OP = 'DELETE' then OLD else NEW end;
end;
$audit$;

drop trigger if exists audit_reservations on public.reservations;
create trigger audit_reservations after insert or update or delete on public.reservations
for each row execute function public.audit_row_change();

drop trigger if exists audit_suggestions on public.gift_suggestions;
create trigger audit_suggestions after insert or update or delete on public.gift_suggestions
for each row execute function public.audit_row_change();

drop trigger if exists audit_contributions on public.contributions;
create trigger audit_contributions after insert or update or delete on public.contributions
for each row execute function public.audit_row_change();

drop trigger if exists audit_ideas on public.ideas;
create trigger audit_ideas after insert or update or delete on public.ideas
for each row execute function public.audit_row_change();

drop trigger if exists audit_messages on public.messages;
create trigger audit_messages after insert or update or delete on public.messages
for each row execute function public.audit_row_change();

drop trigger if exists audit_community_posts on public.community_posts;
create trigger audit_community_posts after insert or update or delete on public.community_posts
for each row execute function public.audit_row_change();

drop trigger if exists audit_community_reactions on public.community_reactions;
create trigger audit_community_reactions after insert or update or delete on public.community_reactions
for each row execute function public.audit_row_change();

drop trigger if exists audit_fundraisers on public.fundraisers;
create trigger audit_fundraisers after insert or update or delete on public.fundraisers
for each row execute function public.audit_row_change();

create or replace function public.log_site_visit(p_page text, p_name text default null)
returns bigint
language plpgsql
security definer
set search_path = ''
as $visit$
declare new_id bigint;
begin
  insert into public.audit_logs(actor_name, action, entity_type, details)
  values (
    coalesce(nullif(trim(p_name), ''), 'Visiteur'),
    'consultée',
    'Visite',
    left(coalesce(trim(p_page), 'Site'), 80)
  )
  returning id into new_id;
  return new_id;
end;
$visit$;

grant execute on function public.log_site_visit(text,text) to anon;

create or replace function public.admin_list_activity()
returns setof public.audit_logs
language plpgsql
security definer
set search_path = ''
as $list$
begin
  perform public.assert_admin_header();
  return query
  select *
  from public.audit_logs
  order by created_at desc
  limit 500;
end;
$list$;

grant execute on function public.admin_list_activity() to anon;

create or replace function public.admin_activity_daily()
returns table (
  day date,
  total bigint,
  visits bigint,
  reservations bigint,
  contributions bigint,
  messages bigint,
  ideas bigint,
  suggestions bigint,
  community bigint,
  fundraisers bigint,
  reactions bigint
)
language plpgsql
security definer
set search_path = ''
as $daily$
begin
  perform public.assert_admin_header();
  return query
  with days as (
    select generate_series(current_date - 6, current_date, interval '1 day')::date as day
  )
  select
    d.day,
    count(a.id) as total,
    count(a.id) filter (where a.entity_type = 'Visite') as visits,
    count(a.id) filter (where a.entity_type = 'Réservation') as reservations,
    count(a.id) filter (where a.entity_type = 'Participation') as contributions,
    count(a.id) filter (where a.entity_type = 'Message') as messages,
    count(a.id) filter (where a.entity_type = 'Idée') as ideas,
    count(a.id) filter (where a.entity_type = 'Suggestion') as suggestions,
    count(a.id) filter (where a.entity_type = 'Communauté') as community,
    count(a.id) filter (where a.entity_type = 'Cagnotte') as fundraisers,
    count(a.id) filter (where a.entity_type = 'Réaction') as reactions
  from days d
  left join public.audit_logs a
    on a.created_at::date = d.day
  group by d.day
  order by d.day;
end;
$daily$;

grant execute on function public.admin_activity_daily() to anon;

create or replace function public.admin_activity_summary()
returns table (
  total bigint,
  visits bigint,
  reservations bigint,
  contributions bigint,
  messages bigint,
  ideas bigint,
  suggestions bigint,
  community bigint,
  fundraisers bigint,
  reactions bigint
)
language plpgsql
security definer
set search_path = ''
as $summary$
begin
  perform public.assert_admin_header();
  return query
  select
    count(*) as total,
    count(*) filter (where entity_type = 'Visite') as visits,
    count(*) filter (where entity_type = 'Réservation') as reservations,
    count(*) filter (where entity_type = 'Participation') as contributions,
    count(*) filter (where entity_type = 'Message') as messages,
    count(*) filter (where entity_type = 'Idée') as ideas,
    count(*) filter (where entity_type = 'Suggestion') as suggestions,
    count(*) filter (where entity_type = 'Communauté') as community,
    count(*) filter (where entity_type = 'Cagnotte') as fundraisers,
    count(*) filter (where entity_type = 'Réaction') as reactions
  from public.audit_logs;
end;
$summary$;

grant execute on function public.admin_activity_summary() to anon;


-- =====================================================
-- PROFILS DES INVITÉS / PERSONNES DU SITE
-- =====================================================

create table if not exists public.guest_profiles (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 50),
  relation text not null check (relation in ('Ami(e)','Famille','Camarade de classe','Connaissance','Autre')),
  avatar text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.guest_profiles enable row level security;
revoke all on table public.guest_profiles from anon, authenticated;

create unique index if not exists guest_profiles_name_lower_idx
on public.guest_profiles (lower(trim(name)));

create or replace function public.upsert_guest_profile(
  p_name text,
  p_relation text,
  p_avatar text default null,
  p_bio text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $profile$
declare
  profile_id bigint;
begin
  if char_length(trim(coalesce(p_name,''))) < 1
     or char_length(trim(p_name)) > 50
     or p_relation not in ('Ami(e)','Famille','Camarade de classe','Connaissance','Autre')
     or char_length(coalesce(p_avatar,'')) > 4
     or char_length(coalesce(p_bio,'')) > 250
  then
    raise exception 'profil invalide';
  end if;

  insert into public.guest_profiles(name, relation, avatar, bio, updated_at)
  values (
    trim(p_name),
    p_relation,
    nullif(trim(p_avatar),''),
    nullif(trim(p_bio),''),
    now()
  )
  on conflict ((lower(trim(name))))
  do update set
    name = excluded.name,
    relation = excluded.relation,
    avatar = excluded.avatar,
    bio = excluded.bio,
    updated_at = now()
  returning id into profile_id;

  return profile_id;
end;
$profile$;

grant execute on function public.upsert_guest_profile(text,text,text,text) to anon;

create or replace function public.admin_list_guest_profiles()
returns table (
  id bigint,
  name text,
  relation text,
  avatar text,
  bio text,
  created_at timestamptz,
  updated_at timestamptz,
  messages_count bigint,
  ideas_count bigint,
  suggestions_count bigint,
  contributions_count bigint,
  community_count bigint
)
language plpgsql
security definer
set search_path = public
as $people$
begin
  perform public.assert_admin_header();
  return query
  select
    p.id,
    p.name,
    p.relation,
    p.avatar,
    p.bio,
    p.created_at,
    p.updated_at,
    (select count(*) from public.messages m where lower(trim(m.name))=lower(trim(p.name))) as messages_count,
    (select count(*) from public.ideas i where lower(trim(i.name))=lower(trim(p.name))) as ideas_count,
    (select count(*) from public.gift_suggestions s where lower(trim(s.name))=lower(trim(p.name))) as suggestions_count,
    (select count(*) from public.contributions c where lower(trim(c.name))=lower(trim(p.name))) as contributions_count,
    (select count(*) from public.community_posts cp where lower(trim(cp.name))=lower(trim(p.name))) as community_count
  from public.guest_profiles p
  order by p.updated_at desc;
end;
$people$;

grant execute on function public.admin_list_guest_profiles() to anon;


-- ============================================================
-- LISTE D'ANNIVERSAIRE PRIVÉE : catalogue + codes d'accès
-- Les cadeaux ne sont plus stockés dans index.html.
-- Le navigateur ne peut récupérer le catalogue qu'avec un code actif.
-- ============================================================

create table if not exists public.gift_catalog (
  id text primary key,
  sort_order integer not null default 0,
  cat text not null,
  title text not null,
  price text not null,
  description text not null,
  image text,
  official_label text,
  official_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.gift_catalog enable row level security;
revoke all on table public.gift_catalog from anon, authenticated;

alter table public.gift_catalog
add column if not exists archived boolean not null default false;

create table if not exists public.list_access_codes (
  id bigint generated by default as identity primary key,
  label text not null check (char_length(trim(label)) between 1 and 80),
  code text not null unique check (char_length(trim(code)) between 8 and 64),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);

create table if not exists public.list_access_authorizations (
  id bigint generated by default as identity primary key,
  access_id bigint not null references public.list_access_codes(id) on delete cascade,
  authorized_at timestamptz not null default now()
);

alter table public.list_access_authorizations enable row level security;
revoke all on table public.list_access_authorizations from anon, authenticated;

alter table public.list_access_codes enable row level security;
revoke all on table public.list_access_codes from anon, authenticated;
alter table public.list_access_codes add column if not exists is_admin boolean not null default false;

-- Protection anti-brute-force de l'authentification des codes d'accès.
-- Le compteur est basé sur l'IP vue par la passerelle Supabase et se réinitialise
-- après une authentification réussie. Aucun code d'accès n'est stocké dans cette table.
create table if not exists public.list_access_rate_limits (
  client_ip text primary key,
  failed_attempts integer not null default 0,
  last_failed_at timestamptz,
  blocked_until timestamptz
);

alter table public.list_access_rate_limits enable row level security;
revoke all on table public.list_access_rate_limits from anon, authenticated;

-- ============================================================
-- TÉLÉMÉTRIE DE L'EXTENSION — CONSENTEMENT EXPLICITE
-- Les données sont envoyées uniquement après acceptation dans
-- l'extension. Aucun mot de passe ou code d'accès n'est collecté.
-- ============================================================

create table if not exists public.extension_telemetry_events (
  id bigint generated by default as identity primary key,
  installation_id uuid not null,
  session_id uuid not null,
  event_type text not null check (
    event_type in (
      'consent_granted',
      'page_view',
      'click',
      'resize',
      'network_online',
      'network_offline',
      'visibility_hidden'
    )
  ),
  page_path text not null check (
    char_length(trim(page_path)) between 1 and 220
    and position('?' in page_path) = 0
    and position('#' in page_path) = 0
  ),
  event_label text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists extension_telemetry_events_created_at_idx
  on public.extension_telemetry_events (created_at desc);

create index if not exists extension_telemetry_events_installation_idx
  on public.extension_telemetry_events (installation_id, created_at desc);

create index if not exists extension_telemetry_events_session_idx
  on public.extension_telemetry_events (session_id, created_at desc);

alter table public.extension_telemetry_events enable row level security;
revoke all on table public.extension_telemetry_events from anon, authenticated;

create or replace function public.extension_log_event(
  p_installation_id uuid,
  p_session_id uuid,
  p_event_type text,
  p_page_path text,
  p_event_label text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $telemetry$
declare
  v_id bigint;
  v_type text;
  v_page text;
  v_label text;
  v_meta jsonb;
begin
  v_type := lower(trim(coalesce(p_event_type, '')));
  v_page := trim(coalesce(p_page_path, ''));
  v_label := nullif(left(trim(coalesce(p_event_label, '')), 160), '');

  if p_installation_id is null or p_session_id is null then
    raise exception 'Identifiant de télémétrie invalide.';
  end if;

  if v_type not in (
    'consent_granted',
    'page_view',
    'click',
    'resize',
    'network_online',
    'network_offline',
    'visibility_hidden'
  ) then
    raise exception 'Type d''événement invalide.';
  end if;

  if char_length(v_page) < 1
     or char_length(v_page) > 220
     or position('?' in v_page) > 0
     or position('#' in v_page) > 0
     or left(v_page, 1) <> '/'
  then
    raise exception 'Page invalide.';
  end if;

  p_metadata := coalesce(p_metadata, '{}'::jsonb);
  if jsonb_typeof(p_metadata) <> 'object' then
    p_metadata := '{}'::jsonb;
  end if;

  -- Liste blanche des informations techniques réellement conservées.
  v_meta := jsonb_strip_nulls(jsonb_build_object(
    'title', left(coalesce(p_metadata->>'title',''), 160),
    'language', left(coalesce(p_metadata->>'language',''), 20),
    'timezone', left(coalesce(p_metadata->>'timezone',''), 80),
    'online', left(coalesce(p_metadata->>'online',''), 10),
    'colorScheme', left(coalesce(p_metadata->>'colorScheme',''), 10),
    'touchPoints', left(coalesce(p_metadata->>'touchPoints',''), 10),
    'connectionType', left(coalesce(p_metadata->>'connectionType',''), 20),
    'viewportWidth', left(coalesce(p_metadata->>'viewportWidth',''), 10),
    'viewportHeight', left(coalesce(p_metadata->>'viewportHeight',''), 10),
    'screenWidth', left(coalesce(p_metadata->>'screenWidth',''), 10),
    'screenHeight', left(coalesce(p_metadata->>'screenHeight',''), 10),
    'extensionVersion', left(coalesce(p_metadata->>'extensionVersion',''), 20)
  ));

  insert into public.extension_telemetry_events(
    installation_id,
    session_id,
    event_type,
    page_path,
    event_label,
    metadata
  )
  values(
    p_installation_id,
    p_session_id,
    v_type,
    v_page,
    v_label,
    v_meta
  )
  returning id into v_id;

  return v_id;
end;
$telemetry$;

grant execute on function public.extension_log_event(uuid,uuid,text,text,text,jsonb) to anon;

create or replace function public.admin_list_extension_events(
  p_limit integer default 250
)
returns table(
  event_id bigint,
  installation_id uuid,
  session_id uuid,
  event_type text,
  page_path text,
  event_label text,
  metadata jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $admintelemetry$
begin
  perform public.assert_admin_header();

  return query
  select
    e.id,
    e.installation_id,
    e.session_id,
    e.event_type,
    e.page_path,
    e.event_label,
    e.metadata,
    e.created_at
  from public.extension_telemetry_events e
  order by e.created_at desc
  limit greatest(1, least(coalesce(p_limit, 250), 500));
end;
$admintelemetry$;

grant execute on function public.admin_list_extension_events(integer) to anon;

create or replace function public.admin_extension_telemetry_stats()
returns table(
  total_events bigint,
  installations bigint,
  sessions bigint,
  active_installations_24h bigint,
  events_24h bigint,
  page_views_24h bigint
)
language plpgsql
security definer
set search_path = public
as $admintelemetrystats$
begin
  perform public.assert_admin_header();

  return query
  select
    count(*)::bigint,
    count(distinct installation_id)::bigint,
    count(distinct session_id)::bigint,
    count(distinct installation_id) filter (where created_at >= now() - interval '24 hours')::bigint,
    count(*) filter (where created_at >= now() - interval '24 hours')::bigint,
    count(*) filter (
      where event_type = 'page_view'
        and created_at >= now() - interval '24 hours'
    )::bigint
  from public.extension_telemetry_events;
end;
$admintelemetrystats$;

grant execute on function public.admin_extension_telemetry_stats() to anon;


create or replace function public.authorize_list_access(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $auth$
declare
  v_id bigint;
  v_label text;
  v_is_admin boolean;
  v_ip text;
  v_attempts integer := 0;
  v_blocked_until timestamptz;
  v_retry integer := 0;
begin
  -- Supabase expose l'IP cliente via les en-têtes de requête.
  v_ip := left(coalesce(
    current_setting('request.headers', true)::json->>'cf-connecting-ip',
    split_part(current_setting('request.headers', true)::json->>'x-forwarded-for', ',', 1),
    current_setting('request.headers', true)::json->>'x-real-ip',
    'unknown'
  ), 120);
  v_ip := nullif(trim(v_ip), '');
  if v_ip is null then v_ip := 'unknown'; end if;

  select failed_attempts, blocked_until
    into v_attempts, v_blocked_until
  from public.list_access_rate_limits
  where client_ip = v_ip;

  if v_blocked_until is not null and v_blocked_until > now() then
    v_retry := greatest(1, ceil(extract(epoch from (v_blocked_until-now())))::integer);
    return jsonb_build_object(
      'authorized', false,
      'rate_limited', true,
      'retry_after_seconds', v_retry
    );
  end if;

  select lac.id, lac.label, lac.is_admin
    into v_id, v_label, v_is_admin
  from public.list_access_codes as lac
  where lac.active = true
    and lac.code = trim(coalesce(p_code, ''))
  limit 1;

  if v_id is null then
    v_attempts := coalesce(v_attempts,0) + 1;
    v_retry := case
      when v_attempts >= 20 then 300
      when v_attempts >= 12 then 60
      when v_attempts >= 8 then 15
      when v_attempts >= 5 then 5
      else 0
    end;

    insert into public.list_access_rate_limits(client_ip,failed_attempts,last_failed_at,blocked_until)
    values(
      v_ip,
      v_attempts,
      now(),
      case when v_retry > 0 then now() + make_interval(secs => v_retry) else null end
    )
    on conflict (client_ip) do update
      set failed_attempts=excluded.failed_attempts,
          last_failed_at=excluded.last_failed_at,
          blocked_until=excluded.blocked_until;

    return jsonb_build_object(
      'authorized', false,
      'rate_limited', v_retry > 0,
      'retry_after_seconds', v_retry
    );
  end if;

  -- Une authentification correcte remet le compteur à zéro.
  delete from public.list_access_rate_limits where client_ip = v_ip;

  update public.list_access_codes as lac
  set last_used_at = now()
  where lac.id = v_id;

  insert into public.list_access_authorizations(access_id, authorized_at)
  values(v_id, now());

  return jsonb_build_object(
    'authorized', true,
    'access_id', v_id,
    'label', v_label,
    'is_admin', v_is_admin
  );
end;
$auth$;

grant execute on function public.authorize_list_access(text) to anon;

drop function if exists public.get_private_gifts(text);

create or replace function public.get_private_gifts(p_code text)
returns table (
  id text,sort_order integer,cat text,title text,price text,description text,image text,
  official_label text,official_url text,target_amount numeric,allow_contributions boolean,
  allow_reservation boolean,funding_note text,contributed_amount numeric,remaining_amount numeric,
  contribution_count bigint,participant_count bigint,my_contribution_count bigint,my_contributed_amount numeric,reserved_by text
)
language plpgsql security definer set search_path=public
as $$
begin
  if not exists(select 1 from public.list_access_codes where active=true and code=trim(coalesce(p_code,''))) then return; end if;
  return query
  select g.id,g.sort_order,g.cat,g.title,g.price,g.description,g.image,g.official_label,g.official_url,
    g.target_amount,g.allow_contributions,g.allow_reservation,g.funding_note,
    coalesce((select sum(c.amount) from public.gift_contributions c where c.gift_id=g.id),0)::numeric,
    greatest(g.target_amount-coalesce((select sum(c.amount) from public.gift_contributions c where c.gift_id=g.id),0),0)::numeric,
    (select count(*) from public.gift_contributions c where c.gift_id=g.id),
    (select count(distinct lower(trim(c.name))) from public.gift_contributions c where c.gift_id=g.id),
    (select count(*) from public.gift_contributions c where c.gift_id=g.id and lower(trim(c.name)) = lower(trim((select lac.label from public.list_access_codes lac where lac.active=true and lac.code=trim(coalesce(p_code,'')) limit 1)))),
    (select coalesce(sum(c.amount),0)::numeric from public.gift_contributions c where c.gift_id=g.id and lower(trim(c.name)) = lower(trim((select lac.label from public.list_access_codes lac where lac.active=true and lac.code=trim(coalesce(p_code,'')) limit 1)))),
    (select r.name from public.reservations r where r.gift_id=g.id limit 1)
  from public.gift_catalog g
  where coalesce(g.archived,false) = false
  order by g.sort_order,g.id;
end;
$$;

grant execute on function public.get_private_gifts(text) to anon;

create or replace function public.add_private_gift_contribution(
  p_code text,p_gift_id text,p_name text,p_amount numeric,p_message text default null
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare v_target numeric;v_current numeric;v_remaining numeric;v_allow boolean;v_id bigint;v_name text;
begin
  select label into v_name from public.list_access_codes
  where active=true and code=trim(coalesce(p_code,'')) limit 1;
  if v_name is null then raise exception 'Accès refusé.' using errcode='42501'; end if;
  select target_amount,allow_contributions into v_target,v_allow from public.gift_catalog where id=p_gift_id for update;
  if v_target is null then raise exception 'Cadeau introuvable.'; end if;
  if not v_allow then raise exception 'Les participations ne sont pas activées pour ce cadeau.'; end if;
  if p_amount is null or p_amount<=0 or p_amount>50000 then raise exception 'Montant invalide.'; end if;
  if exists(select 1 from public.reservations where gift_id=p_gift_id) then raise exception 'Ce cadeau est déjà réservé en totalité.'; end if;
  select coalesce(sum(amount),0) into v_current from public.gift_contributions where gift_id=p_gift_id;
  v_remaining:=greatest(v_target-v_current,0);
  if v_remaining<=0 then raise exception 'Ce cadeau est déjà entièrement financé.'; end if;
  if p_amount>v_remaining then raise exception 'Le maximum est % €.',to_char(v_remaining,'FM999999990.00'); end if;
  insert into public.gift_contributions(gift_id,name,amount,message)
  values(p_gift_id,v_name,round(p_amount,2),nullif(trim(p_message),''))
  returning id into v_id;
  return v_id;
end;
$$;

drop function if exists public.admin_list_gift_catalog();

create or replace function public.admin_list_gift_catalog()
returns table (
  id text,sort_order integer,cat text,title text,price text,description text,image text,
  official_label text,official_url text,target_amount numeric,allow_contributions boolean,
  allow_reservation boolean,funding_note text,contributed_amount numeric,remaining_amount numeric,
  contribution_count bigint,participant_count bigint,reserved_by text
)
language plpgsql security definer set search_path=public
as $$
begin
  perform public.assert_admin_header();
  return query
  select g.id,g.sort_order,g.cat,g.title,g.price,g.description,g.image,g.official_label,g.official_url,
    g.target_amount,g.allow_contributions,g.allow_reservation,g.funding_note,
    coalesce((select sum(c.amount) from public.gift_contributions c where c.gift_id=g.id),0)::numeric,
    greatest(g.target_amount-coalesce((select sum(c.amount) from public.gift_contributions c where c.gift_id=g.id),0),0)::numeric,
    (select count(*) from public.gift_contributions c where c.gift_id=g.id),
    (select count(distinct lower(trim(c.name))) from public.gift_contributions c where c.gift_id=g.id),
    (select r.name from public.reservations r where r.gift_id=g.id limit 1)
  from public.gift_catalog g order by g.sort_order,g.id;
end;
$$;

grant execute on function public.admin_list_gift_catalog() to anon;

create or replace function public.admin_save_gift(
  p_id text,p_sort_order integer,p_cat text,p_title text,p_price text,p_description text,
  p_target_amount numeric,p_allow_contributions boolean,p_allow_reservation boolean,
  p_image text default null,p_official_label text default null,p_official_url text default null,p_funding_note text default null
)
returns text language plpgsql security definer set search_path=public
as $$
begin
  perform public.assert_admin_header();
  if char_length(trim(coalesce(p_id,'')))<1 or char_length(trim(p_id))>80 then raise exception 'Identifiant invalide.'; end if;
  if char_length(trim(coalesce(p_title,'')))<1 or char_length(trim(p_title))>160 then raise exception 'Nom du cadeau invalide.'; end if;
  if p_target_amount is null or p_target_amount<0 then raise exception 'Objectif invalide.'; end if;
  insert into public.gift_catalog
  (id,sort_order,cat,title,price,description,target_amount,allow_contributions,allow_reservation,image,official_label,official_url,funding_note,updated_at)
  values(trim(p_id),coalesce(p_sort_order,0),trim(coalesce(p_cat,'')),trim(p_title),trim(coalesce(p_price,'')),
    trim(coalesce(p_description,'')),p_target_amount,coalesce(p_allow_contributions,false),coalesce(p_allow_reservation,true),
    nullif(trim(p_image),''),nullif(trim(p_official_label),''),nullif(trim(p_official_url),''),nullif(trim(p_funding_note),''),now())
  on conflict(id) do update set
    sort_order=excluded.sort_order,cat=excluded.cat,title=excluded.title,price=excluded.price,description=excluded.description,
    target_amount=excluded.target_amount,allow_contributions=excluded.allow_contributions,allow_reservation=excluded.allow_reservation,
    image=excluded.image,official_label=excluded.official_label,official_url=excluded.official_url,funding_note=excluded.funding_note,updated_at=now();
  return trim(p_id);
end;
$$;

grant execute on function public.admin_save_gift(text,integer,text,text,text,text,numeric,boolean,boolean,text,text,text,text) to anon;

create or replace function public.admin_delete_gift(p_id text)
returns boolean language plpgsql security definer set search_path=public
as $$
declare n integer;
begin
  perform public.assert_admin_header();
  delete from public.gift_contributions where gift_id=p_id;
  delete from public.reservations where gift_id=p_id;
  delete from public.gift_catalog where id=p_id;
  get diagnostics n=row_count;
  return n>0;
end;
$$;

grant execute on function public.admin_delete_gift(text) to anon;

create or replace function public.list_private_gift_contributions(
  p_code text,
  p_gift_id text
)
returns table(
  id bigint,
  amount numeric,
  message text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $privategiftlist$
declare
  v_name text;
begin
  select label
  into v_name
  from public.list_access_codes
  where active = true
    and code = trim(coalesce(p_code, ''))
  limit 1;

  if v_name is null then
    raise exception 'Accès refusé.' using errcode = '42501';
  end if;

  return query
  select
    c.id,
    c.amount,
    c.message,
    c.created_at
  from public.gift_contributions c
  where c.gift_id = p_gift_id
    and lower(trim(c.name)) = lower(trim(v_name))
  order by c.created_at desc, c.id desc;
end;
$privategiftlist$;

grant execute on function public.list_private_gift_contributions(text,text) to anon;


create or replace function public.delete_one_private_gift_contribution(
  p_code text,
  p_contribution_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public
as $privategiftdeleteone$
declare
  v_name text;
  v_deleted integer;
begin
  select label
  into v_name
  from public.list_access_codes
  where active = true
    and code = trim(coalesce(p_code, ''))
  limit 1;

  if v_name is null then
    raise exception 'Accès refusé.' using errcode = '42501';
  end if;

  delete from public.gift_contributions
  where id = p_contribution_id
    and lower(trim(name)) = lower(trim(v_name));

  get diagnostics v_deleted = row_count;
  return v_deleted > 0;
end;
$privategiftdeleteone$;

grant execute on function public.delete_one_private_gift_contribution(text,bigint) to anon;

create or replace function public.delete_private_gift_contribution(
  p_code text,
  p_gift_id text
)
returns integer
language plpgsql
security definer
set search_path = public
as $privategiftdelete$
declare
  v_name text;
  v_deleted integer;
begin
  select label
  into v_name
  from public.list_access_codes
  where active = true
    and code = trim(coalesce(p_code, ''))
  limit 1;

  if v_name is null then
    raise exception 'Accès refusé.'
      using errcode = '42501';
  end if;

  delete from public.gift_contributions
  where gift_id = p_gift_id
    and lower(trim(name)) = lower(trim(v_name));

  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$privategiftdelete$;

grant execute on function public.delete_private_gift_contribution(text,text) to anon;

create or replace function public.delete_private_gift_contribution(
  p_code text,
  p_gift_id text
)
returns integer
language plpgsql
security definer
set search_path = public
as $privategiftdelete$
declare
  v_name text;
  v_deleted integer;
begin
  select label into v_name
  from public.list_access_codes
  where active = true
    and code = trim(coalesce(p_code, ''))
  limit 1;

  if v_name is null then
    raise exception 'Accès refusé.' using errcode = '42501';
  end if;

  delete from public.gift_contributions
  where gift_id = p_gift_id
    and lower(trim(name)) = lower(trim(v_name));

  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$privategiftdelete$;

grant execute on function public.delete_private_gift_contribution(text,text) to anon;

create or replace function public.admin_list_gift_contributions()
returns table(id bigint,gift_id text,gift_title text,name text,amount numeric,message text,created_at timestamptz)
language plpgsql security definer set search_path=public
as $$
begin
  perform public.assert_admin_header();
  return query
  select c.id,c.gift_id,g.title,c.name,c.amount,c.message,c.created_at
  from public.gift_contributions c left join public.gift_catalog g on g.id=c.gift_id
  order by c.created_at desc;
end;
$$;

grant execute on function public.admin_list_gift_contributions() to anon;

create or replace function public.admin_delete_gift_contribution(p_id bigint)
returns boolean language plpgsql security definer set search_path=public
as $$
declare n integer;
begin
  perform public.assert_admin_header();
  delete from public.gift_contributions where id=p_id;
  get diagnostics n=row_count;
  return n>0;
end;
$$;

grant execute on function public.admin_delete_gift_contribution(bigint) to anon;

drop function if exists public.admin_list_access_codes();


-- Nouvelle fonction d'administration sans dépendance aux anciennes fonctions d'accès.
create or replace function public.admin_list_people_v2()
returns table(
  access_id bigint,
  label text,
  code text,
  access_active boolean,
  is_admin boolean,
  access_created_at timestamptz,
  last_used_at timestamptz,
  profile_id bigint,
  profile_name text,
  relation text,
  avatar text,
  bio text,
  profile_created_at timestamptz,
  profile_updated_at timestamptz,
  messages_count bigint,
  ideas_count bigint,
  suggestions_count bigint,
  contributions_count bigint,
  community_count bigint
)
language plpgsql
security definer
set search_path = public
as $peoplev2$
begin
  perform public.assert_admin_header();

  return query
  select
    lac.id as access_id,
    lac.label as label,
    lac.code as code,
    lac.active as access_active,
    lac.is_admin as is_admin,
    lac.created_at as access_created_at,
    lac.last_used_at as last_used_at,
    gp.id as profile_id,
    gp.name as profile_name,
    gp.relation as relation,
    gp.avatar as avatar,
    gp.bio as bio,
    gp.created_at as profile_created_at,
    gp.updated_at as profile_updated_at,
    coalesce((select count(*) from public.messages m where lower(trim(m.name)) = lower(trim(lac.label))),0)::bigint as messages_count,
    coalesce((select count(*) from public.ideas i where lower(trim(i.name)) = lower(trim(lac.label))),0)::bigint as ideas_count,
    coalesce((select count(*) from public.gift_suggestions gs where lower(trim(gs.name)) = lower(trim(lac.label))),0)::bigint as suggestions_count,
    coalesce((select count(*) from public.contributions c where lower(trim(c.name)) = lower(trim(lac.label))),0)::bigint as contributions_count,
    coalesce((select count(*) from public.community_posts cp where lower(trim(cp.name)) = lower(trim(lac.label))),0)::bigint as community_count
  from public.list_access_codes as lac
  left join public.guest_profiles as gp
    on lower(trim(gp.name)) = lower(trim(lac.label))
  order by lac.created_at desc;
end;
$peoplev2$;

grant execute on function public.admin_list_people_v2() to anon;

create or replace function public.admin_list_access_codes_v2()
returns table(
  access_id bigint,
  label text,
  code text,
  access_active boolean,
  is_admin boolean,
  access_created_at timestamptz,
  last_used_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $accessv2$
begin
  perform public.assert_admin_header();

  return query
  select
    lac.id as access_id,
    lac.label as label,
    lac.code as code,
    lac.active as access_active,
    lac.is_admin as is_admin,
    lac.created_at as access_created_at,
    lac.last_used_at as last_used_at
  from public.list_access_codes as lac
  order by lac.created_at desc;
end;
$accessv2$;

grant execute on function public.admin_list_access_codes_v2() to anon;

create or replace function public.admin_list_access_codes()
returns table(id bigint,label text,code text,active boolean,is_admin boolean,created_at timestamptz,last_used_at timestamptz)
language plpgsql security definer set search_path=public
as $$
begin
  perform public.assert_admin_header();
  return query
  select lac.id,lac.label,lac.code,lac.active,lac.is_admin,lac.created_at,lac.last_used_at
  from public.list_access_codes as lac
  order by lac.created_at desc;
end;
$$;

grant execute on function public.admin_list_access_codes() to anon;
  
drop function if exists public.admin_list_access_codes_for_code(text);
create or replace function public.admin_list_access_codes_for_code(p_code text)
returns table(
  id bigint,
  label text,
  code text,
  active boolean,
  is_admin boolean,
  created_at timestamptz,
  last_used_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $accesslist$
begin
  if not exists (
    select 1
    from public.list_access_codes
    where active = true
      and is_admin = true
      and code = trim(coalesce(p_code, ''))
  ) then
    raise exception 'Accès administrateur refusé.'
      using errcode = '42501';
  end if;

  return query
  select
    lac.id,
    lac.label,
    lac.code,
    lac.active,
    lac.is_admin,
    lac.created_at,
    lac.last_used_at
  from public.list_access_codes as lac
  order by lac.created_at desc;
end;
$accesslist$;

grant execute on function public.admin_list_access_codes_for_code(text) to anon;



create or replace function public.admin_create_access_code(p_label text,p_code text)
returns bigint language plpgsql security definer set search_path=public
as $$
declare v_id bigint;
begin
  perform public.assert_admin_header();
  if char_length(trim(coalesce(p_label,'')))<1 or char_length(trim(p_label))>80 then raise exception 'Nom invalide.'; end if;
  if char_length(trim(coalesce(p_code,'')))<8 or char_length(trim(p_code))>64 then raise exception 'Code trop court ou trop long.'; end if;
  insert into public.list_access_codes(label,code,active) values(trim(p_label),trim(p_code),true) returning id into v_id;
  return v_id;
end;
$$;

grant execute on function public.admin_create_access_code(text,text) to anon;

create or replace function public.admin_set_access_code_admin(p_id bigint,p_is_admin boolean)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
begin
  perform public.assert_admin_header();
  update public.list_access_codes
  set is_admin=coalesce(p_is_admin,false)
  where id=p_id;
  return found;
end;
$$;

grant execute on function public.admin_set_access_code_admin(bigint,boolean) to anon;

create or replace function public.admin_set_access_code_status(p_id bigint,p_active boolean)
returns boolean language plpgsql security definer set search_path=public
as $$
begin
  perform public.assert_admin_header(); update public.list_access_codes set active=coalesce(p_active,false) where id=p_id; return found; end;
$$;

grant execute on function public.admin_set_access_code_status(bigint,boolean) to anon;

create or replace function public.admin_delete_access_code(p_id bigint)
returns boolean language plpgsql security definer set search_path=public
as $$
begin
  perform public.assert_admin_header(); delete from public.list_access_codes where id=p_id; return found; end;
$$;

grant execute on function public.admin_delete_access_code(bigint) to anon;

drop trigger if exists audit_gift_contributions on public.gift_contributions;
create trigger audit_gift_contributions after insert or update or delete on public.gift_contributions
for each row execute function public.audit_row_change();

drop trigger if exists audit_gift_catalog on public.gift_catalog;
create trigger audit_gift_catalog after insert or update or delete on public.gift_catalog
for each row execute function public.audit_row_change();



-- ============================================================
-- SYNCHRONISATION DES ABONNEMENTS MAGAZINES
-- Offre Trio Disney + Chroniques de Fantomiald
-- ============================================================

insert into public.gift_catalog (
  id, sort_order, cat, title, price, description,
  target_amount, allow_contributions, allow_reservation,
  image, official_label, official_url, funding_note, archived, updated_at
)
values (
  'picsou-magazine', 16, 'Abonnements Disney', 'Offre Trio Disney Magazines',
  '99,00 € / an',
  'Picsou Magazine (8 n°/an) + Super Picsou Géant (6 n°/an) + Les Trésors de Picsou (4 n°/an). Durée : 1 an. Bonus : 1er mois offert avec le code 1MOIS sur Disney Magazines.',
  99.00, true, true,
  null, 'Disney Magazines', 'https://www.disneymagazines.fr/titre/picsou-magazine',
  'Total indicatif avec Les Chroniques de Fantomiald : ~125,00 € / an pour les 4 titres. Bonus : 1er mois offert avec le code 1MOIS sur Disney Magazines.',
  false, now()
)
on conflict (id) do update set
  sort_order=excluded.sort_order,
  cat=excluded.cat,
  title=excluded.title,
  price=excluded.price,
  description=excluded.description,
  target_amount=excluded.target_amount,
  allow_contributions=excluded.allow_contributions,
  allow_reservation=excluded.allow_reservation,
  image=excluded.image,
  official_label=excluded.official_label,
  official_url=excluded.official_url,
  funding_note=excluded.funding_note,
  archived=false,
  updated_at=now();

insert into public.gift_catalog (
  id, sort_order, cat, title, price, description,
  target_amount, allow_contributions, allow_reservation,
  image, official_label, official_url, funding_note, archived, updated_at
)
values (
  'picsou-integral', 17, 'Abonnements Disney', 'Les Chroniques de Fantomiald',
  '~26,00 € / an',
  'Les Chroniques de Fantomiald (4 n°/an). Durée : 1 an.',
  26.00, true, true,
  null, 'A2Presse', 'https://www.a2presse.fr/abonnement-magazine-les-chroniques-de-fantomiald.html',
  'Avec l’Offre Trio Disney Magazines : ~125,00 € / an au total pour les 4 titres.',
  false, now()
)
on conflict (id) do update set
  sort_order=excluded.sort_order,
  cat=excluded.cat,
  title=excluded.title,
  price=excluded.price,
  description=excluded.description,
  target_amount=excluded.target_amount,
  allow_contributions=excluded.allow_contributions,
  allow_reservation=excluded.allow_reservation,
  image=excluded.image,
  official_label=excluded.official_label,
  official_url=excluded.official_url,
  funding_note=excluded.funding_note,
  archived=false,
  updated_at=now();

-- Les anciennes offres sont conservées en base pour l’historique,
-- mais masquées de la liste publique.
update public.gift_catalog
set archived=true,
    updated_at=now()
where id in ('journal-mickey','picsou-mickey-pack');


notify pgrst,'reload schema';

-- Schéma rechargé après les changements d'accès.

-- ============================================================
-- CENTRE ANNIVERSAIRE
-- 1 compte à rebours, 2 mode anniversaire, 3 programme masqué
-- par défaut, quiz, sondages, défis, mur, galerie, souvenirs.
-- ============================================================

create table if not exists public.birthday_config (
  id bigint primary key default 1 check (id=1),
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.birthday_config enable row level security;
revoke all on public.birthday_config from anon, authenticated;

insert into public.birthday_config(id,settings)
values (
  1,
  jsonb_build_object(
    'countdown_at','2026-12-23T00:00:00+01:00',
    'birthday_mode',false,
    'schedule_visible',false,
    'schedule',jsonb_build_array(),
    'quiz',jsonb_build_object('enabled',false,'title','Qui connaît Ethan ?','questions',jsonb_build_array()),
    'poll',jsonb_build_object('enabled',false,'title','Que fait-on maintenant ?','options',jsonb_build_array()),
    'challenges',jsonb_build_array(),
    'wall',jsonb_build_object('enabled',false,'title','Mur des messages'),
    'gallery',jsonb_build_object('enabled',false,'items',jsonb_build_array()),
    'memories',jsonb_build_object('enabled',false,'title','Souvenirs de l’anniversaire','intro','','stats',jsonb_build_array()),
    'murder_party',jsonb_build_object(
      'enabled',false,
      'title','Dossier Hydra — Murder Party',
      'date','23 décembre 2026',
      'players',jsonb_build_array(
        jsonb_build_object('name','Ethan','role','Chef Hydra','function','Coordinateur central, cerveau de l’enquête.','special','Ordre du Chef Hydra','fragment','Fragment IA 1 : Le protocole Hydra-Core a été déclenché avant l’incident.'),
        jsonb_build_object('name','Serge','role','Patient Hydra','function','Patient chronique, témoin clé.','special','Dossier Médical Hydra','fragment','Fragment IA 2 : Traces Alpha détectées sur un sujet vivant.'),
        jsonb_build_object('name','Silvie','role','Protectrice du Livre Ancien','function','Gardienne du secret, mémoire du livre.','special','Extrait du Livre Ancien','fragment','Fragment IA 3 : La page manquante contient l’identité réelle de la victime.'),
        jsonb_build_object('name','Fabrice','role','Archiviste Numérique Hydra','function','Gestion des données et archives.','special','Dossier OSINT','fragment','Fragment IA 4 : Altération du fichier vidéo. Horodatage incohérent.'),
        jsonb_build_object('name','Jean-Louis Pineau','role','Pilote de l’Île Flottante','function','Navigation et contrôle des déplacements.','special','Journal de Navigation','fragment','Fragment IA 5 : Déviation de trajectoire enregistrée à 21h52.'),
        jsonb_build_object('name','Jean-Louis Meal','role','Espion Hydra','function','Infiltration, surveillance.','special','Ordre Secret Hydra','fragment','Fragment IA 6 : Un individu a été observé deux fois au même endroit.'),
        jsonb_build_object('name','Cécile','role','Sentinelle Hydra','function','Observation, surveillance.','special','Rapport d’Observation','fragment','Fragment IA 7 : Silhouette identique détectée à 22h14.'),
        jsonb_build_object('name','Annie','role','Matriarche Hydra','function','Mémoire familiale depuis 40 ans.','special','Mémoire Familiale','fragment','Fragment IA 8 : Les deux lignées ne forment qu’une seule famille.'),
        jsonb_build_object('name','Max','role','Agent OSINT','function','Analyse numérique, métadonnées.','special','Message Crypté','fragment','Fragment IA 9 : Il n’est pas celui que vous croyez.'),
        jsonb_build_object('name','Yoan','role','Saboteur Repenti','function','Manipulation technique.','special','Schéma de Sabotage','fragment','Fragment IA 10 : Sabotage mineur enregistré. Impact imprévu.'),
        jsonb_build_object('name','Marie-Françoise','role','Gardienne des Bijoux Hydra','function','Gestion des bijoux traceurs.','special','Inventaire des Bijoux Hydra','fragment','Fragment IA 11 : Bijou 3 : signal détecté près d’un sujet instable.'),
        jsonb_build_object('name','Claudie','role','Psychologue Hydra','function','Profilage mental, analyse comportementale.','special','Profil Mental Hydra','fragment','Fragment IA 12 : Comportement altéré après exposition Omega.'),
        jsonb_build_object('name','Andrea','role','Protectrice des Animaux Hydra','function','Gestion et interprétation de Milo.','special','Rapport Milo','fragment','Fragment IA 13 : Zone 3 : traces Omega détectées par unité biologique.'),
        jsonb_build_object('name','Mario','role','Gardien de Milo','function','Suivi du chien détecteur.','special','Note de Terrain','fragment','Fragment IA 14 : Objet Hydra trouvé à 20h31.'),
        jsonb_build_object('name','Tony','role','Mini-Analyste OSINT','function','Analyse visuelle, QR codes, symboles.','special','Symbole Hydra','fragment','Fragment IA 15 : Symbole Hydra associé au protocole Omega.'),
        jsonb_build_object('name','Lino','role','Gardien des Objets Hydra','function','Protection des reliques.','special','Objet Sacré Hydra','fragment','Fragment IA 16 : L’objet sacré est lié à l’identité de la victime.'),
        jsonb_build_object('name','Emy','role','Secrétaire du Chef Hydra','function','Assistance opérationnelle.','special','Ordre du Chef Hydra','fragment','Fragment IA 17 : Fragment IA distribué par ordre du Chef.'),
        jsonb_build_object('name','Milo','role','Chien Détecteur Hydra','function','Détection biologique des poisons.','special','Carte des Zones Reniflées','fragment','Fragment IA 18 : Zone 2 : traces Alpha détectées.')
      )
    )
  )
)
on conflict(id) do nothing;

create table if not exists public.birthday_interactions (
  id bigint generated by default as identity primary key,
  interaction_type text not null check (
    interaction_type in ('quiz_result','poll_vote','challenge_done','wall_message','gallery_submission')
  ),
  visitor_name text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.birthday_interactions enable row level security;
revoke all on public.birthday_interactions from anon, authenticated;

drop function if exists public.get_birthday_config();

create or replace function public.get_birthday_config()
returns jsonb
language plpgsql
security definer
set search_path=public
as $adminbirthdayconfig$
begin
  perform public.assert_admin_header();
  return (
    select coalesce(settings,'{}'::jsonb)
    from public.birthday_config
    where id=1
  );
end;
$adminbirthdayconfig$;

grant execute on function public.get_birthday_config() to anon;

create or replace function public.get_birthday_public_config()
returns jsonb
language sql
security definer
set search_path=public
as $birthdaypublicconfig$
  select jsonb_strip_nulls(
    coalesce(settings,'{}'::jsonb)
    - 'murder_party'
    - 'schedule'
  ) ||
  jsonb_build_object(
    'schedule',
      case
        when coalesce((settings->>'schedule_visible')::boolean,false)
        then coalesce(settings->'schedule','[]'::jsonb)
        else '[]'::jsonb
      end
  )
  from public.birthday_config
  where id=1;
$birthdaypublicconfig$;

grant execute on function public.get_birthday_public_config() to anon;

create or replace function public.admin_save_birthday_config(p_settings jsonb)
returns boolean
language plpgsql
security definer
set search_path=public
as $adminbirthday$
begin
  perform public.assert_admin_header();
  if p_settings is null or jsonb_typeof(p_settings) <> 'object' then
    raise exception 'Configuration anniversaire invalide.';
  end if;
  update public.birthday_config
  set settings=p_settings, updated_at=now()
  where id=1;
  return found;
end;
$adminbirthday$;

grant execute on function public.admin_save_birthday_config(jsonb) to anon;

create or replace function public.submit_birthday_interaction(
  p_code text,
  p_type text,
  p_payload jsonb
)
returns bigint
language plpgsql
security definer
set search_path=public
as $birthdayinteraction$
declare
  v_id bigint;
  v_name text;
begin
  select label into v_name
  from public.list_access_codes
  where active=true and code=trim(coalesce(p_code,''))
  limit 1;

  if v_name is null then
    raise exception 'Accès refusé.' using errcode='42501';
  end if;

  if p_type not in ('quiz_result','poll_vote','challenge_done','wall_message','gallery_submission') then
    raise exception 'Type d’interaction invalide.';
  end if;

  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'Données invalides.';
  end if;

  insert into public.birthday_interactions(interaction_type,visitor_name,payload)
  values(p_type,trim(v_name),p_payload)
  returning id into v_id;

  return v_id;
end;
$birthdayinteraction$;

grant execute on function public.submit_birthday_interaction(text,text,jsonb) to anon;

create or replace function public.get_birthday_interactions(
  p_code text,
  p_type text
)
returns table(
  visitor_name text,
  payload jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public
as $birthdaypublic$
begin
  if not exists(
    select 1 from public.list_access_codes
    where active=true and code=trim(coalesce(p_code,''))
  ) then
    raise exception 'Accès refusé.' using errcode='42501';
  end if;

  return query
  select visitor_name,payload,created_at
  from public.birthday_interactions
  where interaction_type=trim(p_type)
  order by created_at desc
  limit 500;
end;
$birthdaypublic$;

grant execute on function public.get_birthday_interactions(text,text) to anon;

create or replace function public.admin_list_birthday_interactions()
returns table(
  id bigint,
  interaction_type text,
  visitor_name text,
  payload jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public
as $adminbirthdayinteractions$
begin
  perform public.assert_admin_header();
  return query
  select i.id,i.interaction_type,i.visitor_name,i.payload,i.created_at
  from public.birthday_interactions i
  order by i.created_at desc
  limit 500;
end;
$adminbirthdayinteractions$;

grant execute on function public.admin_list_birthday_interactions() to anon;


-- IMPORTANT : ce bloc doit être exécuté dans l’éditeur SQL Supabase pour créer/mettre à jour les fonctions du Centre anniversaire.
-- Le fichier GitHub seul ne modifie pas le schéma Supabase.
notify pgrst,'reload schema';
