create table if not exists public.reservations (
  gift_id text primary key,
  name text not null check (char_length(trim(name)) between 1 and 50),
  created_at timestamptz not null default now()
);

alter table public.reservations enable row level security;

drop policy if exists "Public can view reservations" on public.reservations;
create policy "Public can view reservations"
on public.reservations for select
to anon
using (true);

drop policy if exists "Public can create reservations" on public.reservations;
create policy "Public can create reservations"
on public.reservations for insert
to anon
with check (char_length(trim(name)) between 1 and 50);

-- Autorisations PostgREST pour les visiteurs non connectés
grant usage on schema public to anon;
grant select, insert on table public.reservations to anon;

-- Autoriser la déréservation depuis le site
grant delete on table public.reservations to anon;

drop policy if exists "Public can cancel reservations" on public.reservations;
create policy "Public can cancel reservations"
on public.reservations
for delete
to anon
using (true);

-- Fonction serveur pour déréserver un cadeau en vérifiant le prénom
create or replace function public.cancel_reservation(p_gift_id text, p_name text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted boolean;
begin
  delete from public.reservations
  where gift_id = p_gift_id
    and lower(trim(name)) = lower(trim(p_name))
  returning true into deleted;

  return coalesce(deleted, false);
end;
$$;

grant execute on function public.cancel_reservation(text, text) to anon;

-- Suggestions de cadeaux
create table if not exists public.gift_suggestions (
  id bigint generated by default as identity primary key,
  name text,
  gift_name text not null check (char_length(trim(gift_name)) between 1 and 120),
  link text,
  message text,
  created_at timestamptz not null default now()
);

alter table public.gift_suggestions enable row level security;

drop policy if exists "Public can view gift suggestions" on public.gift_suggestions;
create policy "Public can view gift suggestions"
on public.gift_suggestions for select
to anon
using (true);

drop policy if exists "Public can create gift suggestions" on public.gift_suggestions;
create policy "Public can create gift suggestions"
on public.gift_suggestions for insert
to anon
with check (char_length(trim(gift_name)) between 1 and 120);

grant select, insert on table public.gift_suggestions to anon;
grant usage, select on sequence public.gift_suggestions_id_seq to anon;

-- Participations financières annoncées (aucun paiement n'est effectué ici)
create table if not exists public.contributions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 50),
  amount numeric(10,2) not null check (amount >= 1 and amount <= 5000),
  message text,
  created_at timestamptz not null default now()
);

alter table public.contributions enable row level security;

drop policy if exists "Public can view contributions" on public.contributions;
create policy "Public can view contributions"
on public.contributions for select
to anon
using (true);

drop policy if exists "Public can create contributions" on public.contributions;
create policy "Public can create contributions"
on public.contributions for insert
to anon
with check (
  char_length(trim(name)) between 1 and 50
  and amount >= 1
  and amount <= 5000
);

grant select, insert on table public.contributions to anon;
grant usage, select on sequence public.contributions_id_seq to anon;
