(()=>{
'use strict';
if(window.__hydraPixLayer)return;window.__hydraPixLayer=true;
const KEY='hydra_vm_learning_state_v1';
const missions=[
{id:'m01',title:'Prise en main',level:'INITIATION',app:'Dashboard',text:'Repère les trois outils utiles à une enquête numérique.',goal:'Ouvrir Intelligence, Evidence et Terminal.',hint:'Utilise le lanceur HYDRA HUB en bas à gauche.'},
{id:'m02',title:'Trace financière',level:'FACILE',app:'Finance',text:'Retrouve la transaction qui mérite une vérification.',goal:'Ouvrir Finance et sélectionner la transaction suspecte.',hint:'Cherche le mouvement de 2,3 M€ vers une structure écran.'},
{id:'m03',title:'Fragment IA',level:'INTERMÉDIAIRE',app:'Intelligence',text:'Recoupe les fragments sans dépendre d’un seul indice.',goal:'Ouvrir Intelligence puis consulter les fragments.',hint:'Si une piste physique manque, cherche sa trace numérique.'},
{id:'m04',title:'Terminal Hydra',level:'INTERMÉDIAIRE',app:'Terminal',text:'Utilise l’aide avant d’explorer les commandes.',goal:'Ouvrir Terminal et afficher l’aide.',hint:'Tape help : les commandes doivent t’expliquer quoi faire.'},
{id:'m05',title:'Recoupement final',level:'AVANCÉ',app:'Evidence',text:'Rassemble plusieurs familles d’indices avant de conclure.',goal:'Ouvrir Evidence Locker et examiner plusieurs pièces.',hint:'Une conclusion importante doit pouvoir être obtenue par plusieurs chemins.'}
];
let state=Object.assign({started:{},done:{},hints:{},seen:{},zoom:100},JSON.parse(localStorage.getItem(KEY)||'{}'));state.started=state.started||{};state.done=state.done||{};state.hints=state.hints||{};state.seen=state.seen||{};state.zoom=state.zoom||100;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const style=document.createElement('style');style.textContent='#hydraPixHub{position:fixed;left:18px;bottom:18px;z-index:100000;font-family:Inter,system-ui,sans-serif}#hydraPixHub .hub-btn{border:1px solid #5066ff;background:linear-gradient(135deg,#28348d,#146b91);color:#fff;border-radius:14px;padding:11px 14px;font-weight:900;box-shadow:0 12px 35px #0008;cursor:pointer}#hydraPixPanel{position:fixed;left:18px;bottom:72px;width:min(680px,calc(100vw - 36px));max-height:min(78vh,720px);overflow:auto;background:#09111d;color:#eaf2ff;border:1px solid #344d70;border-radius:20px;box-shadow:0 25px 80px #000b;padding:18px;display:none}#hydraPixPanel.open{display:block}.pix-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:14px}.pix-head h2{margin:0;font-size:20px}.pix-close,.pix-tools button,.pix-actions button{border:1px solid #334963;background:#111d2d;color:#dce7f7;border-radius:9px;padding:8px 10px;cursor:pointer;font-weight:800}.pix-search{width:100%;padding:11px;border-radius:10px;border:1px solid #334963;background:#07101a;color:#fff;margin-bottom:12px}.pix-tools{display:flex;gap:6px;flex-wrap:wrap;margin:12px 0}.pix-progress{height:9px;background:#18253a;border-radius:99px;overflow:hidden;margin:7px 0 14px}.pix-progress i{display:block;height:100%;background:linear-gradient(90deg,#6978ff,#34d6ff);width:0}.pix-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.pix-card{border:1px solid #293e5d;background:#0d1726;border-radius:13px;padding:12px}.pix-card.done{border-color:#2e775d;background:#0d211b}.pix-card b{display:block}.pix-card small{color:#8499b6}.pix-card p{font-size:12px;line-height:1.45;color:#cbd7e8}.pix-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.pix-actions .primary{background:#3f51b5;border-color:#7180ff;color:#fff}.pix-hint{margin-top:9px;padding:9px;border-left:3px solid #ffd071;background:#1e190d;color:#f4dca7;font-size:11px}.pix-mobile-note{display:none;color:#8fa5c1;font-size:11px}@media(max-width:640px){#hydraPixHub{left:10px;bottom:10px}.pix-grid{grid-template-columns:1fr}.pix-mobile-note{display:block}#hydraPixPanel{left:8px;bottom:62px;width:calc(100vw - 16px);max-height:84vh}}body.hydra-focus-mode #hydraPixHub .hub-btn{border-radius:50%;width:48px;height:48px;padding:0}';document.head.appendChild(style);
const host=document.createElement('div');host.id='hydraPixHub';host.innerHTML='<button class="hub-btn" aria-label="Ouvrir HYDRA HUB">◈ HUB</button><section id="hydraPixPanel" aria-label="HYDRA HUB"><div class="pix-head"><div><h2>HYDRA HUB</h2><small>Centre de missions et d’apprentissage</small></div><button class="pix-close">Fermer</button></div><input class="pix-search" aria-label="Rechercher une mission" placeholder="Rechercher une mission ou une application…"><div class="pix-tools"><button data-action="focus">Mode concentration</button><button data-action="zoom-out">A−</button><button data-action="zoom-reset">100%</button><button data-action="zoom-in">A+</button><button data-action="help">Aide clavier</button></div><div class="pix-mobile-note">Sur téléphone : une application à la fois est recommandée.</div><div><b id="pixCount">0 / 5 missions</b><div class="pix-progress"><i id="pixProgress"></i></div></div><div class="pix-grid" id="pixGrid"></div></section>';document.body.appendChild(host);
const panel=host.querySelector('#hydraPixPanel'),grid=host.querySelector('#pixGrid');
function openApp(id){try{window.__hydraStartVM?.();window.activateHydraTab?.(id,true);document.querySelector('[data-vm-section="'+id+'"]')?.click()}catch(e){console.warn('HYDRA HUB',e)}}
function render(filter){filter=filter||'';const q=filter.toLowerCase();grid.innerHTML=missions.filter(m=>(m.title+' '+m.app+' '+m.text).toLowerCase().includes(q)).map(m=>{const done=!!state.done[m.id],hint=state.hints[m.id];return '<article class="pix-card '+(done?'done':'')+'"><b>'+esc(m.title)+'</b><small>'+esc(m.level)+' · '+esc(m.app)+'</small><p>'+esc(m.text)+'</p><small>Objectif : '+esc(m.goal)+'</small><div class="pix-actions"><button class="primary" data-open="'+m.app.toLowerCase()+'">Ouvrir</button><button data-done="'+m.id+'">'+(done?'Mission validée':'Valider')+'</button><button data-hint="'+m.id+'">Indice</button></div>'+(hint?'<div class="pix-hint">'+esc(m.hint)+'</div>':'')+'</article>'}).join('')||'<div class="pix-card">Aucune mission trouvée.</div>';const n=Object.values(state.done).filter(Boolean).length;host.querySelector('#pixCount').textContent=n+' / '+missions.length+' missions';host.querySelector('#pixProgress').style.width=(n/missions.length*100)+'%'}
function setZoom(v){state.zoom=Math.max(90,Math.min(130,v));document.body.style.fontSize=state.zoom+'%';save()}function help(){alert('Raccourcis HYDRA HUB\n\nCtrl+K : ouvrir le HUB\nÉchap : fermer\nCtrl+Shift+F : mode concentration\n+ / − : taille du texte\nH : afficher les indices')}
host.querySelector('.hub-btn').onclick=()=>{panel.classList.toggle('open');if(panel.classList.contains('open'))render()};host.querySelector('.pix-close').onclick=()=>panel.classList.remove('open');host.querySelector('.pix-search').oninput=e=>render(e.target.value);
grid.addEventListener('click',e=>{const o=e.target.closest('[data-open]'),d=e.target.closest('[data-done]'),h=e.target.closest('[data-hint]');if(o){const map={dashboard:'dashboard',finance:'finance',mail:'mails',intelligence:'intelligence',terminal:'terminal',evidence:'evidence'};openApp(map[o.dataset.open]||o.dataset.open);return}if(d){state.done[d.dataset.done]=true;save();render(host.querySelector('.pix-search').value);return}if(h){state.hints[h.dataset.hint]=true;save();render(host.querySelector('.pix-search').value)}});
host.querySelectorAll('.pix-tools button').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='focus')document.body.classList.toggle('hydra-focus-mode');if(a==='zoom-in')setZoom(state.zoom+10);if(a==='zoom-out')setZoom(state.zoom-10);if(a==='zoom-reset')setZoom(100);if(a==='help')help()});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();panel.classList.add('open');render();host.querySelector('.pix-search').focus()}if(e.key==='Escape')panel.classList.remove('open');if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='f'){e.preventDefault();document.body.classList.toggle('hydra-focus-mode')}if(e.key==='+'||e.key==='=')setZoom(state.zoom+10);if(e.key==='-')setZoom(state.zoom-10);if(e.key.toLowerCase()==='h'){state.hints.m01=true;save();if(panel.classList.contains('open'))render()}});
setZoom(state.zoom);window.__hydraPixHub={render,openApp,state};setTimeout(()=>{try{window.__hydraStartVM?.()}catch(e){}render()},900);
})();